In [1]:
import pandas as pd
import psycopg2 as pg
import numpy as np
import datetime as dt
import warnings
import json
warnings.filterwarnings("ignore")
engine = pg.connect("dbname='dvdrental' user='postgres' host='127.0.0.1' port='5432' password='python'")
df = pd.read_sql('select * from actor', con=engine)


# SORGULAR

## SORGU 1: 

- select * from public.film ;
- film listesini tüm kolonları ile birlikte çeker

In [2]:
df_film = pd.read_sql('select * from film', con=engine)

In [3]:
df_film


film_id              title  \
0        133    Chamber Italian   
1        384   Grosse Wonderful   
2          8    Airport Pollock   
3         98  Bright Encounters   
4          1   Academy Dinosaur   
..       ...                ...   
995      996     Young Language   
996      997         Youth Kick   
997      998       Zhivago Core   
998      999  Zoolander Fiction   
999     1000          Zorro Ark   

                                           description  release_year  \
0    A Fateful Reflection of a Moose And a Husband ...          2006   
1    A Epic Drama of a Cat And a Explorer who must ...          2006   
2    A Epic Tale of a Moose And a Girl who must Con...          2006   
3    A Fateful Yarn of a Lumberjack And a Feminist ...          2006   
4    A Epic Drama of a Feminist And a Mad Scientist...          2006   
..                                                 ...           ...   
995  A Unbelieveable Yarn of a Boat And a Database ...          2006   
996  A Touching Drama of a Teacher And a Cat who mu...          2006   
997  A Fateful Yarn of a Composer And a Man who mus...          2006   
998  A Fateful Reflection of a Waitress And a Boat ...          2006   
999  A Intrepid Panorama of a Mad Scientist And a B...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
0              1                7         4.99     117             14.99   
1              1                5         4.99      49             19.99   
2              1                6         4.99      54             15.99   
3              1                4         4.99      73             12.99   
4              1                6         0.99      86             20.99   
..           ...              ...          ...     ...               ...   
995            1                6         0.99     183              9.99   
996            1                4         0.99     179             14.99   
997            1                6         0.99     105             10.99   
998            1                5         2.99     101             28.99   
999            1                3         4.99      50             18.99   

    rating             last_update  \
0    NC-17 2013-05-26 14:50:58.951   
1        R 2013-05-26 14:50:58.951   
2        R 2013-05-26 14:50:58.951   
3    PG-13 2013-05-26 14:50:58.951   
4       PG 2013-05-26 14:50:58.951   
..     ...                     ...   
995      G 2013-05-26 14:50:58.951   
996  NC-17 2013-05-26 14:50:58.951   
997  NC-17 2013-05-26 14:50:58.951   
998      R 2013-05-26 14:50:58.951   
999  NC-17 2013-05-26 14:50:58.951   

                                special_features  \
0                                     [Trailers]   
1                            [Behind the Scenes]   
2                                     [Trailers]   
3                                     [Trailers]   
4            [Deleted Scenes, Behind the Scenes]   
..                                           ...   
995                [Trailers, Behind the Scenes]   
996                [Trailers, Behind the Scenes]   
997                             [Deleted Scenes]   
998                   [Trailers, Deleted Scenes]   
999  [Trailers, Commentaries, Behind the Scenes]   

                                              fulltext  
0    'chamber':1 'fate':4 'husband':11 'italian':2 ...  
1    'australia':18 'cat':8 'drama':5 'epic':4 'exp...  
2    'airport':1 'ancient':18 'confront':14 'epic':...  
3    'boat':20 'bright':1 'conquer':14 'encount':2 ...  
4    'academi':1 'battl':15 'canadian':20 'dinosaur...  
..                                                 ...  
995  'administr':12 'boat':8 'boy':17 'databas':11 ...  
996  'boat':22 'cat':11 'challeng':14 'drama':5 'ki...  
997  'boy':16 'canadian':19 'compos':8 'core':2 'fa...  
998  'ancient':19 'boat':11 'china':20 'discov':14 ...  
999  'ark':2 'boy':12,17 'intrepid':4 'mad':8 'mona...  

[1000 rows x 13 columns]

## Sorgu 2: 
- select file_id,title from public.film ;
- film listesini sadece istenilen kolonları ile birlikte çeker

In [4]:
col_names= ["film_id", "title"]
df_film[col_names]

film_id              title
0        133    Chamber Italian
1        384   Grosse Wonderful
2          8    Airport Pollock
3         98  Bright Encounters
4          1   Academy Dinosaur
..       ...                ...
995      996     Young Language
996      997         Youth Kick
997      998       Zhivago Core
998      999  Zoolander Fiction
999     1000          Zorro Ark

[1000 rows x 2 columns]

## Sorgu 3: 
-  SELECT film_id, title as film_adi, description, release_year, language_id, rental_duration, rental_rate, length, replacement_cost, rating, last_update, special_features, fulltext FROM public.film;
- Film listesini çek, listede film isimleri bulunan title alanı kolon adı film_adı olacak şekilde listele

In [5]:
df_film.rename(columns ={'title':'film_adı'})

film_id           film_adı  \
0        133    Chamber Italian   
1        384   Grosse Wonderful   
2          8    Airport Pollock   
3         98  Bright Encounters   
4          1   Academy Dinosaur   
..       ...                ...   
995      996     Young Language   
996      997         Youth Kick   
997      998       Zhivago Core   
998      999  Zoolander Fiction   
999     1000          Zorro Ark   

                                           description  release_year  \
0    A Fateful Reflection of a Moose And a Husband ...          2006   
1    A Epic Drama of a Cat And a Explorer who must ...          2006   
2    A Epic Tale of a Moose And a Girl who must Con...          2006   
3    A Fateful Yarn of a Lumberjack And a Feminist ...          2006   
4    A Epic Drama of a Feminist And a Mad Scientist...          2006   
..                                                 ...           ...   
995  A Unbelieveable Yarn of a Boat And a Database ...          2006   
996  A Touching Drama of a Teacher And a Cat who mu...          2006   
997  A Fateful Yarn of a Composer And a Man who mus...          2006   
998  A Fateful Reflection of a Waitress And a Boat ...          2006   
999  A Intrepid Panorama of a Mad Scientist And a B...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
0              1                7         4.99     117             14.99   
1              1                5         4.99      49             19.99   
2              1                6         4.99      54             15.99   
3              1                4         4.99      73             12.99   
4              1                6         0.99      86             20.99   
..           ...              ...          ...     ...               ...   
995            1                6         0.99     183              9.99   
996            1                4         0.99     179             14.99   
997            1                6         0.99     105             10.99   
998            1                5         2.99     101             28.99   
999            1                3         4.99      50             18.99   

    rating             last_update  \
0    NC-17 2013-05-26 14:50:58.951   
1        R 2013-05-26 14:50:58.951   
2        R 2013-05-26 14:50:58.951   
3    PG-13 2013-05-26 14:50:58.951   
4       PG 2013-05-26 14:50:58.951   
..     ...                     ...   
995      G 2013-05-26 14:50:58.951   
996  NC-17 2013-05-26 14:50:58.951   
997  NC-17 2013-05-26 14:50:58.951   
998      R 2013-05-26 14:50:58.951   
999  NC-17 2013-05-26 14:50:58.951   

                                special_features  \
0                                     [Trailers]   
1                            [Behind the Scenes]   
2                                     [Trailers]   
3                                     [Trailers]   
4            [Deleted Scenes, Behind the Scenes]   
..                                           ...   
995                [Trailers, Behind the Scenes]   
996                [Trailers, Behind the Scenes]   
997                             [Deleted Scenes]   
998                   [Trailers, Deleted Scenes]   
999  [Trailers, Commentaries, Behind the Scenes]   

                                              fulltext  
0    'chamber':1 'fate':4 'husband':11 'italian':2 ...  
1    'australia':18 'cat':8 'drama':5 'epic':4 'exp...  
2    'airport':1 'ancient':18 'confront':14 'epic':...  
3    'boat':20 'bright':1 'conquer':14 'encount':2 ...  
4    'academi':1 'battl':15 'canadian':20 'dinosaur...  
..                                                 ...  
995  'administr':12 'boat':8 'boy':17 'databas':11 ...  
996  'boat':22 'cat':11 'challeng':14 'drama':5 'ki...  
997  'boy':16 'canadian':19 'compos':8 'core':2 'fa...  
998  'ancient':19 'boat':11 'china':20 'discov':14 ...  
999  'ark':2 'boy':12,17 'intrepid':4 'mad':8 'mona...  

[1000 rows x 13 columns]

## Sorgu 4: 
- select * from public.film order by length asc;
- film listesini uzunluğa göre küçükten büyüğe sıralar

In [6]:
df_film.sort_values('length')

film_id                title  \
503      504        Kwai Homeward   
18        15         Alien Center   
468      469            Iron Moon   
504      505     Labyrinth League   
730      730  Ridgemont Submarine   
..       ...                  ...   
426      426            Home Pity   
349      349          Gangs Pride   
609      609        Muscle Bright   
690      690         Pond Seattle   
214      212       Darn Forrester   

                                           description  release_year  \
503  A Amazing Drama of a Car And a Squirrel who mu...          2006   
18   A Brilliant Drama of a Cat And a Mad Scientist...          2006   
468  A Fast-Paced Documentary of a Mad Cow And a Bo...          2006   
504  A Awe-Inspiring Saga of a Composer And a Frisb...          2006   
730  A Unbelieveable Drama of a Waitress And a Comp...          2006   
..                                                 ...           ...   
426  A Touching Panorama of a Man And a Secret Agen...          2006   
349  A Taut Character Study of a Woman And a A Shar...          2006   
609  A Stunning Panorama of a Sumo Wrestler And a H...          2006   
690  A Stunning Drama of a Teacher And a Boat who m...          2006   
214  A Fateful Story of a A Shark And a Explorer wh...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
503            1                5         0.99      46             25.99   
18             1                5         2.99      46             10.99   
468            1                7         4.99      46             27.99   
504            1                6         2.99      46             24.99   
730            1                3         0.99      46             28.99   
..           ...              ...          ...     ...               ...   
426            1                7         4.99     185             15.99   
349            1                4         2.99     185             27.99   
609            1                7         2.99     185             23.99   
690            1                7         2.99     185             25.99   
214            1                7         4.99     185             14.99   

    rating             last_update  \
503  PG-13 2013-05-26 14:50:58.951   
18   NC-17 2013-05-26 14:50:58.951   
468     PG 2013-05-26 14:50:58.951   
504  PG-13 2013-05-26 14:50:58.951   
730  PG-13 2013-05-26 14:50:58.951   
..     ...                     ...   
426      R 2013-05-26 14:50:58.951   
349  PG-13 2013-05-26 14:50:58.951   
609      G 2013-05-26 14:50:58.951   
690  PG-13 2013-05-26 14:50:58.951   
214      G 2013-05-26 14:50:58.951   

                                      special_features  \
503                           [Trailers, Commentaries]   
18         [Trailers, Commentaries, Behind the Scenes]   
468                  [Commentaries, Behind the Scenes]   
504                  [Commentaries, Behind the Scenes]   
730  [Commentaries, Deleted Scenes, Behind the Scenes]   
..                                                 ...   
426        [Trailers, Commentaries, Behind the Scenes]   
349                                [Behind the Scenes]   
609                                   [Deleted Scenes]   
690        [Trailers, Commentaries, Behind the Scenes]   
214                                   [Deleted Scenes]   

                                              fulltext  
503  'amaz':4 'car':8,16 'drama':5 'georgia':19 'ho...  
18   'alien':1 'battl':15 'brilliant':4 'cat':8 'ce...  
468  'baloon':22 'boy':14 'cow':11 'dentist':19 'do...  
504  'awe':5 'awe-inspir':4 'compos':10 'desert':22...  
730  'ancient':19 'compos':11 'cow':17 'drama':5 'j...  
..                                                 ...  
426  'agent':12 'challeng':15 'convent':21 'home':1...  
349  'berlin':20 'charact':5 'confront':16 'frisbe'...  
609  'ancient':19 'bright':2 'husband':12 'india':2...  
690  'ancient':18 'battl':14 'boat':11 'china':19 '...  
2

## Sorgu 5: 
- select * from public.film order by length desc;
- film listesini uzunluğa göre büyükten küçüğe göre sıralar



In [7]:
df_film.sort_values('length', ascending=False)

film_id                title  \
690      690         Pond Seattle   
873      872    Sweet Brotherhood   
426      426            Home Pity   
816      817   Soldiers Evolution   
990      991         Worst Banger   
..       ...                  ...   
468      469            Iron Moon   
730      730  Ridgemont Submarine   
503      504        Kwai Homeward   
504      505     Labyrinth League   
18        15         Alien Center   

                                           description  release_year  \
690  A Stunning Drama of a Teacher And a Boat who m...          2006   
873  A Unbelieveable Epistle of a Sumo Wrestler And...          2006   
426  A Touching Panorama of a Man And a Secret Agen...          2006   
816  A Lacklusture Panorama of a A Shark And a Pion...          2006   
990  A Thrilling Drama of a Madman And a Dentist wh...          2006   
..                                                 ...           ...   
468  A Fast-Paced Documentary of a Mad Cow And a Bo...          2006   
730  A Unbelieveable Drama of a Waitress And a Comp...          2006   
503  A Amazing Drama of a Car And a Squirrel who mu...          2006   
504  A Awe-Inspiring Saga of a Composer And a Frisb...          2006   
18   A Brilliant Drama of a Cat And a Mad Scientist...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
690            1                7         2.99     185             25.99   
873            1                3         2.99     185             27.99   
426            1                7         4.99     185             15.99   
816            1                7         4.99     185             27.99   
990            1                4         2.99     185             26.99   
..           ...              ...          ...     ...               ...   
468            1                7         4.99      46             27.99   
730            1                3         0.99      46             28.99   
503            1                5         0.99      46             25.99   
504            1                6         2.99      46             24.99   
18             1                5         2.99      46             10.99   

    rating             last_update  \
690  PG-13 2013-05-26 14:50:58.951   
873      R 2013-05-26 14:50:58.951   
426      R 2013-05-26 14:50:58.951   
816      R 2013-05-26 14:50:58.951   
990     PG 2013-05-26 14:50:58.951   
..     ...                     ...   
468     PG 2013-05-26 14:50:58.951   
730  PG-13 2013-05-26 14:50:58.951   
503  PG-13 2013-05-26 14:50:58.951   
504  PG-13 2013-05-26 14:50:58.951   
18   NC-17 2013-05-26 14:50:58.951   

                                      special_features  \
690        [Trailers, Commentaries, Behind the Scenes]   
873                                   [Deleted Scenes]   
426        [Trailers, Commentaries, Behind the Scenes]   
816  [Trailers, Commentaries, Deleted Scenes, Behin...   
990                [Deleted Scenes, Behind the Scenes]   
..                                                 ...   
468                  [Commentaries, Behind the Scenes]   
730  [Commentaries, Deleted Scenes, Behind the Scenes]   
503                           [Trailers, Commentaries]   
504                  [Commentaries, Behind the Scenes]   
18         [Trailers, Commentaries, Behind the Scenes]   

                                              fulltext  
690  'ancient':18 'battl':14 'boat':11 'china':19 '...  
873  'baloon':21 'brotherhood':2 'chase':15 'epistl...  
426  'agent':12 'challeng':15 'convent':21 'home':1...  
816  'confront':15 'evolut':2 'first':20 'lacklustu...  
990  'banger':2 'boy':16 'conquer':14 'dentist':11 ...  
..                                                 ...  
468  'baloon':22 'boy':14 'cow':11 'dentist':19 'do...  
730  'ancient':19 'compos':11 'cow':17 'drama':5 'j...  
503  'amaz':4 'car':8,16 'drama':5 'georgia':19 'ho...  
504  'awe':5 'awe-inspir':4 'compos':10 'desert':22...  
1

## Sorgu 6: 
- select distinct first_name from customer c 
- bir first_name'den birden fazla var ise sadece bir tanesini listeler. Tekil first_nameleri listeler

In [8]:
df_customer = pd.read_sql('select * from customer', con=engine)

In [9]:
# sadece sayısal değerini görmek istiyorsak: 
df_customer.first_name.nunique()


591

In [10]:
result = df_customer['first_name'].unique()
#print(type(result))
#numpy.ndarray tipinde verir.
#Diğer hücrede tekrar dataframe'e çevrilmiştir.
print(result)

['Jared' 'Mary' 'Patricia' 'Linda' 'Barbara' 'Elizabeth' 'Jennifer'
 'Maria' 'Susan' 'Margaret' 'Dorothy' 'Lisa' 'Nancy' 'Karen' 'Betty'
 'Helen' 'Sandra' 'Donna' 'Carol' 'Ruth' 'Sharon' 'Michelle' 'Laura'
 'Sarah' 'Kimberly' 'Deborah' 'Jessica' 'Shirley' 'Cynthia' 'Angela'
 'Melissa' 'Brenda' 'Amy' 'Anna' 'Rebecca' 'Virginia' 'Kathleen' 'Pamela'
 'Martha' 'Debra' 'Amanda' 'Stephanie' 'Carolyn' 'Christine' 'Marie'
 'Janet' 'Catherine' 'Frances' 'Ann' 'Joyce' 'Diane' 'Alice' 'Julie'
 'Heather' 'Teresa' 'Doris' 'Gloria' 'Evelyn' 'Jean' 'Cheryl' 'Mildred'
 'Katherine' 'Joan' 'Ashley' 'Judith' 'Rose' 'Janice' 'Kelly' 'Nicole'
 'Judy' 'Christina' 'Kathy' 'Theresa' 'Beverly' 'Denise' 'Tammy' 'Irene'
 'Jane' 'Lori' 'Rachel' 'Marilyn' 'Andrea' 'Kathryn' 'Louise' 'Sara'
 'Anne' 'Jacqueline' 'Wanda' 'Bonnie' 'Julia' 'Ruby' 'Lois' 'Tina'
 'Phyllis' 'Norma' 'Paula' 'Diana' 'Annie' 'Lillian' 'Emily' 'Robin'
 'Peggy' 'Crystal' 'Gladys' 'Rita' 'Dawn' 'Connie' 'Florence' 'Tracy'
 'Edna' 'Tiffany' 'Car

In [11]:
first_name= pd.DataFrame(result)
first_name

0
0       Jared
1        Mary
2    Patricia
3       Linda
4     Barbara
..        ...
586  Terrence
587   Enrique
588   Freddie
589      Wade
590    Austin

[591 rows x 1 columns]

## Sorgu 7: 
- select first_name,last_name,'customer' as type   from public.customer union  select first_name,last_name,'actor' as type  from public.actor a

- customer ve actor tablolarında yer alan tüm isimlerin listesini verir,ayrıca type alanında ismin hangi gruba ait olduğu belirtilir. 
 

In [12]:
# iki tablonunda dataframe'e çevrilmesi: 
df_customer = pd.read_sql('select * from customer', con=engine)
df_actor = pd.read_sql('select * from actor', con=engine)

In [13]:
# istenilen tablonun tipini atamak için: 
df_customer["type"] = "customer"
df_customer

customer_id  store_id first_name  last_name  \
0            524         1      Jared        Ely   
1              1         1       Mary      Smith   
2              2         1   Patricia    Johnson   
3              3         1      Linda   Williams   
4              4         2    Barbara      Jones   
..           ...       ...        ...        ...   
594          595         1   Terrence  Gunderson   
595          596         1    Enrique   Forsythe   
596          597         1    Freddie     Duggan   
597          598         1       Wade   Delvalle   
598          599         2     Austin    Cintron   

                                     email  address_id  activebool  \
0             jared.ely@sakilacustomer.org         530        True   
1            mary.smith@sakilacustomer.org           5        True   
2      patricia.johnson@sakilacustomer.org           6        True   
3        linda.williams@sakilacustomer.org           7        True   
4         barbara.jones@sakilacustomer.org           8        True   
..                                     ...         ...         ...   
594  terrence.gunderson@sakilacustomer.org         601        True   
595    enrique.forsythe@sakilacustomer.org         602        True   
596      freddie.duggan@sakilacustomer.org         603        True   
597       wade.delvalle@sakilacustomer.org         604        True   
598      austin.cintron@sakilacustomer.org         605        True   

    create_date             last_update  active      type  
0    2006-02-14 2013-05-26 14:49:45.738       1  customer  
1    2006-02-14 2013-05-26 14:49:45.738       1  customer  
2    2006-02-14 2013-05-26 14:49:45.738       1  customer  
3    2006-02-14 2013-05-26 14:49:45.738       1  customer  
4    2006-02-14 2013-05-26 14:49:45.738       1  customer  
..          ...                     ...     ...       ...  
594  2006-02-14 2013-05-26 14:49:45.738       1  customer  
595  2006-02-14 2013-05-26 14:49:45.738       1  customer  
596  2006-02-14 2013-05-26 14:49:45.738       1  customer  
597  2006-02-14 2013-05-26 14:49:45.738       1  customer  
598  2006-02-14 2013-05-26 14:49:45.738       1  customer  

[599 rows x 11 columns]

In [14]:
# istenilen tablonun tipini atamak için: 
df_actor["type"]= "actor"
df_actor

actor_id first_name     last_name             last_update   type
0           1   Penelope       Guiness 2013-05-26 14:47:57.620  actor
1           2       Nick      Wahlberg 2013-05-26 14:47:57.620  actor
2           3         Ed         Chase 2013-05-26 14:47:57.620  actor
3           4   Jennifer         Davis 2013-05-26 14:47:57.620  actor
4           5     Johnny  Lollobrigida 2013-05-26 14:47:57.620  actor
..        ...        ...           ...                     ...    ...
195       196       Bela        Walken 2013-05-26 14:47:57.620  actor
196       197      Reese          West 2013-05-26 14:47:57.620  actor
197       198       Mary        Keitel 2013-05-26 14:47:57.620  actor
198       199      Julia       Fawcett 2013-05-26 14:47:57.620  actor
199       200      Thora        Temple 2013-05-26 14:47:57.620  actor

[200 rows x 5 columns]

In [15]:
# İki tabloyu birleştirip sadece istenilen sütunları alıyoruz. 
df_concat= pd.concat([df_customer, df_actor])
df_concat[["first_name","last_name","type"]]

first_name last_name      type
0        Jared       Ely  customer
1         Mary     Smith  customer
2     Patricia   Johnson  customer
3        Linda  Williams  customer
4      Barbara     Jones  customer
..         ...       ...       ...
195       Bela    Walken     actor
196      Reese      West     actor
197       Mary    Keitel     actor
198      Julia   Fawcett     actor
199      Thora    Temple     actor

[799 rows x 3 columns]

## Sorgu 8: 
- select first_name from public.customer EXCEPT select first_name from public.actor
- actor tablosunda yer alan first_name lerden customer tablosuyla eşleşen isimleri filtreleyerek sadece customer tablosunda bulunan isimleri listeler




In [16]:
df_actor = pd.read_sql('select * from actor', con=engine)
df_customer = pd.read_sql('select * from customer', con=engine)
result_df = df_customer[~df_customer['first_name'].isin(df_actor['first_name'])]
result_df

customer_id  store_id first_name  last_name  \
0            524         1      Jared        Ely   
2              2         1   Patricia    Johnson   
3              3         1      Linda   Williams   
4              4         2    Barbara      Jones   
5              5         1  Elizabeth      Brown   
..           ...       ...        ...        ...   
594          595         1   Terrence  Gunderson   
595          596         1    Enrique   Forsythe   
596          597         1    Freddie     Duggan   
597          598         1       Wade   Delvalle   
598          599         2     Austin    Cintron   

                                     email  address_id  activebool  \
0             jared.ely@sakilacustomer.org         530        True   
2      patricia.johnson@sakilacustomer.org           6        True   
3        linda.williams@sakilacustomer.org           7        True   
4         barbara.jones@sakilacustomer.org           8        True   
5       elizabeth.brown@sakilacustomer.org           9        True   
..                                     ...         ...         ...   
594  terrence.gunderson@sakilacustomer.org         601        True   
595    enrique.forsythe@sakilacustomer.org         602        True   
596      freddie.duggan@sakilacustomer.org         603        True   
597       wade.delvalle@sakilacustomer.org         604        True   
598      austin.cintron@sakilacustomer.org         605        True   

    create_date             last_update  active  
0    2006-02-14 2013-05-26 14:49:45.738       1  
2    2006-02-14 2013-05-26 14:49:45.738       1  
3    2006-02-14 2013-05-26 14:49:45.738       1  
4    2006-02-14 2013-05-26 14:49:45.738       1  
5    2006-02-14 2013-05-26 14:49:45.738       1  
..          ...                     ...     ...  
594  2006-02-14 2013-05-26 14:49:45.738       1  
595  2006-02-14 2013-05-26 14:49:45.738       1  
596  2006-02-14 2013-05-26 14:49:45.738       1  
597  2006-02-14 2013-05-26 14:49:45.738       1  
598  2006-02-14 2013-05-26 14:49:45.738       1  

[527 rows x 10 columns]

## Sorgu 9: 
- select first_name from public.customer INTERSECT select first_name from public.actor
- Customer ve Actor tablolarının her ikisinde de aynı anda bulunan first_nameleri listeler

In [17]:
df_actor = pd.read_sql('select * from actor', con=engine)
df_customer = pd.read_sql('select * from customer', con=engine)
result = pd.merge(df_customer, df_actor,on="first_name", how='inner')
#result = pd.merge(df1,df2,on='key', how='inner')
result = result[['first_name']].drop_duplicates()
print(result.head())

  first_name
0       Mary
2   Jennifer
3      Susan
5       Lisa
6      Helen


##  Sorgu 10: 
- SELECT first_name,'c' FROM public.customer UNION SELECT first_name,'a' FROM public.actor LIMIT 10
- birleştirilen 2 tablodan 10 kayıt çeker

In [18]:
df_customer = pd.read_sql('select * from customer', con=engine)
df_actor = pd.read_sql('select * from actor', con=engine)


df_customer["type"] = "customer"
df_actor["type"]= "actor"


df_union = pd.concat([df_customer, df_actor]).drop_duplicates(subset=['first_name'])  # union: will remove duplicate rows
df_union
df_union[["first_name","last_name","type"]].head(10)

first_name last_name      type
0      Jared       Ely  customer
1       Mary     Smith  customer
2   Patricia   Johnson  customer
3      Linda  Williams  customer
4    Barbara     Jones  customer
5  Elizabeth     Brown  customer
6   Jennifer     Davis  customer
7      Maria    Miller  customer
8      Susan    Wilson  customer
9   Margaret     Moore  customer

### SQL’s UNION is similar to UNION ALL, however UNION will remove duplicate rows.

## Sorgu 11: 
- SELECT first_name,'c' FROM public.customer UNION (SELECT first_name,'a' FROM public.actor LIMIT 10)
- customer tablosundaki tüm kayıtları, actor tablosundan 10 kaydı çekerek iki sonucu birleştirir.

In [19]:
df_customer = pd.read_sql('select * from customer', con=engine)
df_customer["type"] = "customer"
df_customer

customer_id  store_id first_name  last_name  \
0            524         1      Jared        Ely   
1              1         1       Mary      Smith   
2              2         1   Patricia    Johnson   
3              3         1      Linda   Williams   
4              4         2    Barbara      Jones   
..           ...       ...        ...        ...   
594          595         1   Terrence  Gunderson   
595          596         1    Enrique   Forsythe   
596          597         1    Freddie     Duggan   
597          598         1       Wade   Delvalle   
598          599         2     Austin    Cintron   

                                     email  address_id  activebool  \
0             jared.ely@sakilacustomer.org         530        True   
1            mary.smith@sakilacustomer.org           5        True   
2      patricia.johnson@sakilacustomer.org           6        True   
3        linda.williams@sakilacustomer.org           7        True   
4         barbara.jones@sakilacustomer.org           8        True   
..                                     ...         ...         ...   
594  terrence.gunderson@sakilacustomer.org         601        True   
595    enrique.forsythe@sakilacustomer.org         602        True   
596      freddie.duggan@sakilacustomer.org         603        True   
597       wade.delvalle@sakilacustomer.org         604        True   
598      austin.cintron@sakilacustomer.org         605        True   

    create_date             last_update  active      type  
0    2006-02-14 2013-05-26 14:49:45.738       1  customer  
1    2006-02-14 2013-05-26 14:49:45.738       1  customer  
2    2006-02-14 2013-05-26 14:49:45.738       1  customer  
3    2006-02-14 2013-05-26 14:49:45.738       1  customer  
4    2006-02-14 2013-05-26 14:49:45.738       1  customer  
..          ...                     ...     ...       ...  
594  2006-02-14 2013-05-26 14:49:45.738       1  customer  
595  2006-02-14 2013-05-26 14:49:45.738       1  customer  
596  2006-02-14 2013-05-26 14:49:45.738       1  customer  
597  2006-02-14 2013-05-26 14:49:45.738       1  customer  
598  2006-02-14 2013-05-26 14:49:45.738       1  customer  

[599 rows x 11 columns]

In [20]:
df_actor = pd.read_sql('select * from actor', con=engine)
df_actor =  df_actor.head(10)
df_actor["type"]= "actor"

In [21]:
df_concat = pd.concat([df_customer, df_actor])
df_concat[["first_name","type"]]

first_name      type
0       Jared  customer
1        Mary  customer
2    Patricia  customer
3       Linda  customer
4     Barbara  customer
..        ...       ...
5       Bette     actor
6       Grace     actor
7     Matthew     actor
8         Joe     actor
9   Christian     actor

[609 rows x 2 columns]

## Sorgu 12: 

- select * from film order by film_id limit 10 offset 12
- film_id ye göre sırala ilk 12 satırı atladıktan sonraki ve  kaydı listele.



In [22]:
df_film = pd.read_sql('select * from film', con=engine)
film_sort = df_film.sort_values('film_id')
film_sort.iloc[12:].head(10)

film_id                title  \
16       13          Ali Forever   
17       14       Alice Fantasia   
18       15         Alien Center   
19       16      Alley Evolution   
20       17           Alone Trip   
21       18        Alter Victory   
22       19         Amadeus Holy   
23       20  Amelie Hellfighters   
24       21      American Circus   
25       22    Amistad Midsummer   

                                          description  release_year  \
16  A Action-Packed Drama of a Dentist And a Croco...          2006   
17  A Emotional Drama of a A Shark And a Database ...          2006   
18  A Brilliant Drama of a Cat And a Mad Scientist...          2006   
19  A Fast-Paced Drama of a Robot And a Composer w...          2006   
20  A Fast-Paced Character Study of a Composer And...          2006   
21  A Thoughtful Drama of a Composer And a Feminis...          2006   
22  A Emotional Display of a Pioneer And a Technic...          2006   
23  A Boring Drama of a Woman And a Squirrel who m...          2006   
24  A Insightful Drama of a Girl And a Astronaut w...          2006   
25  A Emotional Character Study of a Dentist And a...          2006   

    language_id  rental_duration  rental_rate  length  replacement_cost  \
16            1                4         4.99     150             21.99   
17            1                6         0.99      94             23.99   
18            1                5         2.99      46             10.99   
19            1                6         2.99     180             23.99   
20            1                3         0.99      82             14.99   
21            1                6         0.99      57             27.99   
22            1                6         0.99     113             20.99   
23            1                4         4.99      79             23.99   
24            1                3         4.99     129             17.99   
25            1                6         2.99      85             10.99   

   rating             last_update  \
16     PG 2013-05-26 14:50:58.951   
17  NC-17 2013-05-26 14:50:58.951   
18  NC-17 2013-05-26 14:50:58.951   
19  NC-17 2013-05-26 14:50:58.951   
20      R 2013-05-26 14:50:58.951   
21  PG-13 2013-05-26 14:50:58.951   
22     PG 2013-05-26 14:50:58.951   
23      R 2013-05-26 14:50:58.951   
24      R 2013-05-26 14:50:58.951   
25      G 2013-05-26 14:50:58.951   

                                     special_features  \
16                [Deleted Scenes, Behind the Scenes]   
17      [Trailers, Deleted Scenes, Behind the Scenes]   
18        [Trailers, Commentaries, Behind the Scenes]   
19                           [Trailers, Commentaries]   
20                      [Trailers, Behind the Scenes]   
21                      [Trailers, Behind the Scenes]   
22  [Commentaries, Deleted Scenes, Behind the Scenes]   
23  [Commentaries, Deleted Scenes, Behind the Scenes]   
24                  [Commentaries, Behind the Scenes]   
25                  [Commentaries, Behind the Scenes]   

                                             fulltext  
16  'action':5 'action-pack':4 'ali':1 'battl':16 ...  
17  'administr':13 'alic':1 'databas':12 'drama':5...  
18  'alien':1 'battl':15 'brilliant':4 'cat':8 'ce...  
19  'alley':1 'astronaut':18 'battl':16 'compos':1...  
20  'abandon':22 'alon':1 'boat':19 'charact':7 'c...  
21  'agent':17 'alter':1 'canadian':20 'compos':8 ...  
22  'amadeus':1 'baloon':20 'battl':15 'display':5...  
23  'ameli':1 'baloon':19 'bore':4 'conquer':14 'd...  
24  'administr':17 'american':1 'astronaut':11 'ci...  
25  'amistad':1 'california':20 'charact':5 'croco...

## Sorgu 13: 

- SELECT *,customer_id+staff_id as sum from payment;
- iki integer kolonun toplanarak yeni kolon oluşturulması


In [23]:
df_payment = pd.read_sql('select * from payment', con=engine)
df_payment["sum"] = df_payment[["customer_id","staff_id"]].sum(axis=1)
df_payment

payment_id  customer_id  staff_id  rental_id  amount  \
0           17503          341         2       1520    7.99   
1           17504          341         1       1778    1.99   
2           17505          341         1       1849    7.99   
3           17506          341         2       2829    2.99   
4           17507          341         2       3130    7.99   
...           ...          ...       ...        ...     ...   
14591       32094          245         2      12682    2.99   
14592       32095          251         1      14107    0.99   
14593       32096          252         2      13756    4.99   
14594       32097          263         1      15293    0.99   
14595       32098          264         2      14243    2.99   

                    payment_date  sum  
0     2007-02-15 22:25:46.996577  343  
1     2007-02-16 17:23:14.996577  342  
2     2007-02-16 22:41:45.996577  342  
3     2007-02-19 19:39:56.996577  343  
4     2007-02-20 17:31:48.996577  343  
...                          ...  ...  
14591 2007-05-14 13:44:29.996577  247  
14592 2007-05-14 13:44:29.996577  252  
14593 2007-05-14 13:44:29.996577  254  
14594 2007-05-14 13:44:29.996577  264  
14595 2007-05-14 13:44:29.996577  266  

[14596 rows x 7 columns]

## Sorgu 14: 

-  SELECT *,customer_id+amount as sum from payment;
- bir integer ve bir double kolonun toplanarak yeni kolon oluşturulması

In [24]:
df_payment = pd.read_sql('select * from payment', con=engine)
df_payment["sum"] = df_payment[["customer_id","amount"]].sum(axis=1)
df_payment

payment_id  customer_id  staff_id  rental_id  amount  \
0           17503          341         2       1520    7.99   
1           17504          341         1       1778    1.99   
2           17505          341         1       1849    7.99   
3           17506          341         2       2829    2.99   
4           17507          341         2       3130    7.99   
...           ...          ...       ...        ...     ...   
14591       32094          245         2      12682    2.99   
14592       32095          251         1      14107    0.99   
14593       32096          252         2      13756    4.99   
14594       32097          263         1      15293    0.99   
14595       32098          264         2      14243    2.99   

                    payment_date     sum  
0     2007-02-15 22:25:46.996577  348.99  
1     2007-02-16 17:23:14.996577  342.99  
2     2007-02-16 22:41:45.996577  348.99  
3     2007-02-19 19:39:56.996577  343.99  
4     2007-02-20 17:31:48.996577  348.99  
...                          ...     ...  
14591 2007-05-14 13:44:29.996577  247.99  
14592 2007-05-14 13:44:29.996577  251.99  
14593 2007-05-14 13:44:29.996577  256.99  
14594 2007-05-14 13:44:29.996577  263.99  
14595 2007-05-14 13:44:29.996577  266.99  

[14596 rows x 7 columns]

## Sorgu 15: 

- select first_name,last_name, first_name ||' '|| last_name as ad_soyad  from public.actor a 
- iki string kolonun birleşerek yeni kolon oluşturma

In [25]:
df_actor = pd.read_sql('select * from actor', con=engine)
df_actor['ad_soyad'] = df_actor['first_name'].astype(str) + ' ' + df_actor['last_name']
df_actor[["first_name","last_name", "ad_soyad"]]

first_name     last_name             ad_soyad
0     Penelope       Guiness     Penelope Guiness
1         Nick      Wahlberg        Nick Wahlberg
2           Ed         Chase             Ed Chase
3     Jennifer         Davis       Jennifer Davis
4       Johnny  Lollobrigida  Johnny Lollobrigida
..         ...           ...                  ...
195       Bela        Walken          Bela Walken
196      Reese          West           Reese West
197       Mary        Keitel          Mary Keitel
198      Julia       Fawcett        Julia Fawcett
199      Thora        Temple         Thora Temple

[200 rows x 3 columns]

## Sorgu 16: 
- select first_name,last_name, first_name ||' '|| 1  as ad_soyad  from public.actor a 
- bir string bir integer alanı birleştirerek yeni kolon oluşturma

In [26]:
df_actor = pd.read_sql('select * from actor', con=engine)
df_actor['int'] = 1 
# python'da bir int ve strinfg değeri toplamak mümkün değildir. Bu yüzden string'e çevrilmiştir. 

df_actor['ad_soyad'] = df_actor['first_name'].astype(str) + " " + df_actor['int'].astype(str)
df_actor[["first_name","last_name", "ad_soyad"]]

first_name     last_name    ad_soyad
0     Penelope       Guiness  Penelope 1
1         Nick      Wahlberg      Nick 1
2           Ed         Chase        Ed 1
3     Jennifer         Davis  Jennifer 1
4       Johnny  Lollobrigida    Johnny 1
..         ...           ...         ...
195       Bela        Walken      Bela 1
196      Reese          West     Reese 1
197       Mary        Keitel      Mary 1
198      Julia       Fawcett     Julia 1
199      Thora        Temple     Thora 1

[200 rows x 3 columns]

## Sorgu 17: 
- 
SELECT amount,
  round(amount::numeric) AS num_round,
  round(amount::double precision) AS dbl_round
FROM payment;
- alanın yuvarlanmasındaki veri tipinin etkisi



In [27]:
df_payment = pd.read_sql('select * from payment', con=engine)
df_payment["amount"].round()


df_payment["num_round"] =df_payment['amount'].apply(np.ceil).round()

df_payment

payment_id  customer_id  staff_id  rental_id  amount  \
0           17503          341         2       1520    7.99   
1           17504          341         1       1778    1.99   
2           17505          341         1       1849    7.99   
3           17506          341         2       2829    2.99   
4           17507          341         2       3130    7.99   
...           ...          ...       ...        ...     ...   
14591       32094          245         2      12682    2.99   
14592       32095          251         1      14107    0.99   
14593       32096          252         2      13756    4.99   
14594       32097          263         1      15293    0.99   
14595       32098          264         2      14243    2.99   

                    payment_date  num_round  
0     2007-02-15 22:25:46.996577        8.0  
1     2007-02-16 17:23:14.996577        2.0  
2     2007-02-16 22:41:45.996577        8.0  
3     2007-02-19 19:39:56.996577        3.0  
4     2007-02-20 17:31:48.996577        8.0  
...                          ...        ...  
14591 2007-05-14 13:44:29.996577        3.0  
14592 2007-05-14 13:44:29.996577        1.0  
14593 2007-05-14 13:44:29.996577        5.0  
14594 2007-05-14 13:44:29.996577        1.0  
14595 2007-05-14 13:44:29.996577        3.0  

[14596 rows x 7 columns]

## Sorgu 18: 

- select f.film_id ,f.title,count(i.inventory_id)  from film f
left join inventory i on f.film_id=i.film_id
group by f.film_id,f.title  
- Tüm Film İsimlerinin yanına dahil oldukları inventory sayılarını listeler (1000 satır döner toplam değeri 0 olan kayıtlarda listede yer alır)



In [28]:
df_film = pd.read_sql('select * from film', con=engine)
df_inventory = pd.read_sql('select * from inventory', con=engine)
# tablo hazırlığı: 

df_left = pd.merge(df_film, df_inventory, on='film_id', how='left')
df_left.groupby(["film_id","title"])["inventory_id"].agg("count")




film_id  title            
1        Academy Dinosaur     8
2        Ace Goldfinger       3
3        Adaptation Holes     4
4        Affair Prejudice     7
5        African Egg          3
                             ..
996      Young Language       2
997      Youth Kick           2
998      Zhivago Core         2
999      Zoolander Fiction    5
1000     Zorro Ark            8
Name: inventory_id, Length: 1000, dtype: int64

## Sorgu 19: 

- select f.film_id ,f.title,count(i.inventory_id)  from film f
right join inventory i on f.film_id=i.film_id
group by f.film_id,f.title
- herhangi bir inventory e dahil olan filmlerin inventory sayılarını listeler (958 satır döner- toplam değeri 0 olan kayıtlar burda listelenmez)

In [29]:
df_film = pd.read_sql('select * from film', con=engine)
df_inventory = pd.read_sql('select * from inventory', con=engine)
#df_inventory
df_join = pd.merge(df_film, df_inventory, on='film_id', how='right')
#df_join
df_join.groupby(["film_id","title"])["inventory_id"].agg("count")

film_id  title            
1        Academy Dinosaur     8
2        Ace Goldfinger       3
3        Adaptation Holes     4
4        Affair Prejudice     7
5        African Egg          3
                             ..
996      Young Language       2
997      Youth Kick           2
998      Zhivago Core         2
999      Zoolander Fiction    5
1000     Zorro Ark            8
Name: inventory_id, Length: 958, dtype: int64

## Sorgu 20: 
- select f.film_id ,f.title,count(i.inventory_id)  from film f
inner join inventory i on f.film_id=i.film_id
group by f.film_id,f.title

- hem inventory listesinde hemde film listesinde bulunan veri kümesine göre filmlerin bulundukları inventory sayılarını listeler

In [30]:
df_film = pd.read_sql('select * from film', con=engine)
df_inventory = pd.read_sql('select * from inventory', con=engine)
#df_inventory
df_join = pd.merge(df_film, df_inventory, on='film_id', how='inner')
#df_join
df_join.groupby(["film_id","title"])["inventory_id"].agg("count")

film_id  title            
1        Academy Dinosaur     8
2        Ace Goldfinger       3
3        Adaptation Holes     4
4        Affair Prejudice     7
5        African Egg          3
                             ..
996      Young Language       2
997      Youth Kick           2
998      Zhivago Core         2
999      Zoolander Fiction    5
1000     Zorro Ark            8
Name: inventory_id, Length: 958, dtype: int64

## Sorgu 21:

- select f.film_id ,f.title,count(i.inventory_id)  from film f
full join inventory i on f.film_id=i.film_id
group by f.film_id,f.title
- hem inventory listesini hemde film listesinin tamamını alarak hesaplama yapar. 

In [31]:
df_film = pd.read_sql('select * from film', con=engine)
df_inventory = pd.read_sql('select * from inventory', con=engine)
#df_inventory
# full join = outer
df_join = pd.merge(df_film, df_inventory, on='film_id', how='outer')
#df_join
df_join.groupby(["film_id","title"])["inventory_id"].agg("count")

film_id  title            
1        Academy Dinosaur     8
2        Ace Goldfinger       3
3        Adaptation Holes     4
4        Affair Prejudice     7
5        African Egg          3
                             ..
996      Young Language       2
997      Youth Kick           2
998      Zhivago Core         2
999      Zoolander Fiction    5
1000     Zorro Ark            8
Name: inventory_id, Length: 1000, dtype: int64

 ## Sorgu 22:
 
 - select * from film 
where rental_rate =4.99
 - rental_rate i 4.99 olan değerleri listeler
 
 
 

In [32]:
df_film = pd.read_sql('select * from film', con=engine)

df_film[(df_film["rental_rate"] == 4.99)]


film_id                 title  \
0        133       Chamber Italian   
1        384      Grosse Wonderful   
2          8       Airport Pollock   
3         98     Bright Encounters   
5          2        Ace Goldfinger   
..       ...                   ...   
984      985  Wonderland Christmas   
988      989   Working Microcosmos   
993      994         Wyoming Storm   
994      995           Yentl Idaho   
999     1000             Zorro Ark   

                                           description  release_year  \
0    A Fateful Reflection of a Moose And a Husband ...          2006   
1    A Epic Drama of a Cat And a Explorer who must ...          2006   
2    A Epic Tale of a Moose And a Girl who must Con...          2006   
3    A Fateful Yarn of a Lumberjack And a Feminist ...          2006   
5    A Astounding Epistle of a Database Administrat...          2006   
..                                                 ...           ...   
984  A Awe-Inspiring Character Study of a Waitress ...          2006   
988  A Stunning Epistle of a Dentist And a Dog who ...          2006   
993  A Awe-Inspiring Panorama of a Robot And a Boat...          2006   
994  A Amazing Display of a Robot And a Astronaut w...          2006   
999  A Intrepid Panorama of a Mad Scientist And a B...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
0              1                7         4.99     117             14.99   
1              1                5         4.99      49             19.99   
2              1                6         4.99      54             15.99   
3              1                4         4.99      73             12.99   
5              1                3         4.99      48             12.99   
..           ...              ...          ...     ...               ...   
984            1                4         4.99     111             19.99   
988            1                4         4.99      74             22.99   
993            1                6         4.99     100             29.99   
994            1                5         4.99      86             11.99   
999            1                3         4.99      50             18.99   

    rating             last_update  \
0    NC-17 2013-05-26 14:50:58.951   
1        R 2013-05-26 14:50:58.951   
2        R 2013-05-26 14:50:58.951   
3    PG-13 2013-05-26 14:50:58.951   
5        G 2013-05-26 14:50:58.951   
..     ...                     ...   
984     PG 2013-05-26 14:50:58.951   
988      R 2013-05-26 14:50:58.951   
993  PG-13 2013-05-26 14:50:58.951   
994      R 2013-05-26 14:50:58.951   
999  NC-17 2013-05-26 14:50:58.951   

                                special_features  \
0                                     [Trailers]   
1                            [Behind the Scenes]   
2                                     [Trailers]   
3                                     [Trailers]   
5                     [Trailers, Deleted Scenes]   
..                                           ...   
984                               [Commentaries]   
988               [Commentaries, Deleted Scenes]   
993                             [Deleted Scenes]   
994     [Trailers, Commentaries, Deleted Scenes]   
999  [Trailers, Commentaries, Behind the Scenes]   

                                              fulltext  
0    'chamber':1 'fate':4 'husband':11 'italian':2 ...  
1    'australia':18 'cat':8 'drama':5 'epic':4 'exp...  
2    'airport':1 'ancient':18 'confront':14 'epic':...  
3    'boat':20 'bright':1 'conquer':14 'encount':2 ...  
5    'ace':1 'administr':9 'ancient':19 'astound':4...  
..                                                 ...  
984  'awe':5 'awe-inspir':4 'car':14 'charact':7 'c...  
988  'ancient':18 'china':19 'dentist':8 'dog':11 '...  
993  'awe':5 'awe-inspir':4 'boat':13,23 'feminist'...  
994  'amaz':4 'astronaut':11 'berlin':18 'display':...  
999  'ark':2 'boy':12,17 'intrepid':4 'mad':8 'mona...  

[33

## Sorgu 23:
- select * from film 
where rental_rate =4.99 and rental_duration=6 
- rental_rate i 4.99 olan aynı zamanda rental_duration ı 6 olan verileri listeler

In [33]:
df_film = pd.read_sql('select * from film', con=engine)

df_film[(df_film["rental_rate"] == 4.99) & (df_film["rental_duration"] == 6)]

film_id                 title  \
2          8       Airport Pollock   
10         7       Airplane Sierra   
12        10      Aladdin Calendar   
35        32  Apocalypse Flamingos   
80        75     Bird Independence   
..       ...                   ...   
901      902     Trading Pinocchio   
943      944          Virgin Daisy   
967      968         Werewolf Lola   
978      979         Witches Panic   
993      994         Wyoming Storm   

                                           description  release_year  \
2    A Epic Tale of a Moose And a Girl who must Con...          2006   
10   A Touching Saga of a Hunter And a Butler who m...          2006   
12   A Action-Packed Tale of a Man And a Lumberjack...          2006   
35   A Astounding Story of a Dog And a Squirrel who...          2006   
80   A Thrilling Documentary of a Car And a Student...          2006   
..                                                 ...           ...   
901  A Emotional Character Study of a Student And a...          2006   
943  A Awe-Inspiring Documentary of a Robot And a M...          2006   
967  A Fanciful Story of a Man And a Sumo Wrestler ...          2006   
978  A Awe-Inspiring Drama of a Secret Agent And a ...          2006   
993  A Awe-Inspiring Panorama of a Robot And a Boat...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
2              1                6         4.99      54             15.99   
10             1                6         4.99      62             28.99   
12             1                6         4.99      63             24.99   
35             1                6         4.99     119             11.99   
80             1                6         4.99     163             14.99   
..           ...              ...          ...     ...               ...   
901            1                6         4.99     170             22.99   
943            1                6         4.99     179             29.99   
967            1                6         4.99      79             19.99   
978            1                6         4.99     100             10.99   
993            1                6         4.99     100             29.99   

    rating             last_update  \
2        R 2013-05-26 14:50:58.951   
10   PG-13 2013-05-26 14:50:58.951   
12   NC-17 2013-05-26 14:50:58.951   
35       R 2013-05-26 14:50:58.951   
80       G 2013-05-26 14:50:58.951   
..     ...                     ...   
901     PG 2013-05-26 14:50:58.951   
943  PG-13 2013-05-26 14:50:58.951   
967      G 2013-05-26 14:50:58.951   
978  NC-17 2013-05-26 14:50:58.951   
993  PG-13 2013-05-26 14:50:58.951   

                                  special_features  \
2                                       [Trailers]   
10                      [Trailers, Deleted Scenes]   
12                      [Trailers, Deleted Scenes]   
35                        [Trailers, Commentaries]   
80               [Commentaries, Behind the Scenes]   
..                                             ...   
901  [Trailers, Deleted Scenes, Behind the Scenes]   
943                  [Trailers, Behind the Scenes]   
967                  [Trailers, Behind the Scenes]   
978              [Commentaries, Behind the Scenes]   
993                               [Deleted Scenes]   

                                              fulltext  
2    'airport':1 'ancient':18 'confront':14 'epic':...  
10   'airplan':1 'boat':20 'butler':11,16 'discov':...  
12   'action':5 'action-pack':4 'aladdin':1 'ancien...  
35   'abandon':19 'amus':20 'apocalyps':1 'astound'...  
80   'bird':1 'canadian':19 'car':8 'documentari':5...  
..                                                 ...  
901  'charact':5 'discov':15 'emot':4 'explor':12 '...  
943  'administr':20 'awe':5 'awe-inspir':4 'daisi':...  
967  'fanci':4 'lola':2 'man':8 'monasteri':20 'mus...  
978  'agent':11 'awe':5 'awe-inspir':4 'drama':7 'f...  
993  'awe':5 'awe-inspir':4 'boat':13

## Sorgu 24: 
- select * from film 
where rental_rate =4.99 or rental_duration=6 
- rental_rate i 4.99 olan veya rental_duration ı 6 olan verileri listeler

In [34]:
df_film = pd.read_sql('select * from film', con=engine)

df_film[(df_film["rental_rate"] == 4.99) | (df_film["rental_duration"] == 6)]

film_id              title  \
0        133    Chamber Italian   
1        384   Grosse Wonderful   
2          8    Airport Pollock   
3         98  Bright Encounters   
4          1   Academy Dinosaur   
..       ...                ...   
993      994      Wyoming Storm   
994      995        Yentl Idaho   
995      996     Young Language   
997      998       Zhivago Core   
999     1000          Zorro Ark   

                                           description  release_year  \
0    A Fateful Reflection of a Moose And a Husband ...          2006   
1    A Epic Drama of a Cat And a Explorer who must ...          2006   
2    A Epic Tale of a Moose And a Girl who must Con...          2006   
3    A Fateful Yarn of a Lumberjack And a Feminist ...          2006   
4    A Epic Drama of a Feminist And a Mad Scientist...          2006   
..                                                 ...           ...   
993  A Awe-Inspiring Panorama of a Robot And a Boat...          2006   
994  A Amazing Display of a Robot And a Astronaut w...          2006   
995  A Unbelieveable Yarn of a Boat And a Database ...          2006   
997  A Fateful Yarn of a Composer And a Man who mus...          2006   
999  A Intrepid Panorama of a Mad Scientist And a B...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
0              1                7         4.99     117             14.99   
1              1                5         4.99      49             19.99   
2              1                6         4.99      54             15.99   
3              1                4         4.99      73             12.99   
4              1                6         0.99      86             20.99   
..           ...              ...          ...     ...               ...   
993            1                6         4.99     100             29.99   
994            1                5         4.99      86             11.99   
995            1                6         0.99     183              9.99   
997            1                6         0.99     105             10.99   
999            1                3         4.99      50             18.99   

    rating             last_update  \
0    NC-17 2013-05-26 14:50:58.951   
1        R 2013-05-26 14:50:58.951   
2        R 2013-05-26 14:50:58.951   
3    PG-13 2013-05-26 14:50:58.951   
4       PG 2013-05-26 14:50:58.951   
..     ...                     ...   
993  PG-13 2013-05-26 14:50:58.951   
994      R 2013-05-26 14:50:58.951   
995      G 2013-05-26 14:50:58.951   
997  NC-17 2013-05-26 14:50:58.951   
999  NC-17 2013-05-26 14:50:58.951   

                                special_features  \
0                                     [Trailers]   
1                            [Behind the Scenes]   
2                                     [Trailers]   
3                                     [Trailers]   
4            [Deleted Scenes, Behind the Scenes]   
..                                           ...   
993                             [Deleted Scenes]   
994     [Trailers, Commentaries, Deleted Scenes]   
995                [Trailers, Behind the Scenes]   
997                             [Deleted Scenes]   
999  [Trailers, Commentaries, Behind the Scenes]   

                                              fulltext  
0    'chamber':1 'fate':4 'husband':11 'italian':2 ...  
1    'australia':18 'cat':8 'drama':5 'epic':4 'exp...  
2    'airport':1 'ancient':18 'confront':14 'epic':...  
3    'boat':20 'bright':1 'conquer':14 'encount':2 ...  
4    'academi':1 'battl':15 'canadian':20 'dinosaur...  
..                                                 ...  
993  'awe':5 'awe-inspir':4 'boat':13,23 'feminist'...  
994  'amaz':4 'astronaut':11 'berlin':18 'display':...  
995  'administr':12 'boat':8 'boy':17 'databas':11 ...  
997  'boy':16 'canadian':19 'compos':8 'core':2 'fa...  
999  'ark':2 'boy':12,17 'intrepid':4 'mad':8 'mona...  

[482 rows x 13 columns]

## Sorgu 25: 

- select * from film 
where (rental_rate =4.99 or rental_duration=6) and length>50  

- rental_rate i 4.99 olan veya rental_duration ı 6 olan verilerden lenght değeri 50 den büyük olanları listeler

In [35]:
df_film = pd.read_sql('select * from film', con=engine)

df_film[((df_film["rental_rate"] == 4.99) | (df_film["rental_duration"] == 6)) & (df_film["length"] > 50)]

film_id              title  \
0        133    Chamber Italian   
2          8    Airport Pollock   
3         98  Bright Encounters   
4          1   Academy Dinosaur   
8          5        African Egg   
..       ...                ...   
992      993     Wrong Behavior   
993      994      Wyoming Storm   
994      995        Yentl Idaho   
995      996     Young Language   
997      998       Zhivago Core   

                                           description  release_year  \
0    A Fateful Reflection of a Moose And a Husband ...          2006   
2    A Epic Tale of a Moose And a Girl who must Con...          2006   
3    A Fateful Yarn of a Lumberjack And a Feminist ...          2006   
4    A Epic Drama of a Feminist And a Mad Scientist...          2006   
8    A Fast-Paced Documentary of a Pastry Chef And ...          2006   
..                                                 ...           ...   
992  A Emotional Saga of a Crocodile And a Sumo Wre...          2006   
993  A Awe-Inspiring Panorama of a Robot And a Boat...          2006   
994  A Amazing Display of a Robot And a Astronaut w...          2006   
995  A Unbelieveable Yarn of a Boat And a Database ...          2006   
997  A Fateful Yarn of a Composer And a Man who mus...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
0              1                7         4.99     117             14.99   
2              1                6         4.99      54             15.99   
3              1                4         4.99      73             12.99   
4              1                6         0.99      86             20.99   
8              1                6         2.99     130             22.99   
..           ...              ...          ...     ...               ...   
992            1                6         2.99     178             10.99   
993            1                6         4.99     100             29.99   
994            1                5         4.99      86             11.99   
995            1                6         0.99     183              9.99   
997            1                6         0.99     105             10.99   

    rating             last_update                          special_features  \
0    NC-17 2013-05-26 14:50:58.951                                [Trailers]   
2        R 2013-05-26 14:50:58.951                                [Trailers]   
3    PG-13 2013-05-26 14:50:58.951                                [Trailers]   
4       PG 2013-05-26 14:50:58.951       [Deleted Scenes, Behind the Scenes]   
8        G 2013-05-26 14:50:58.951                          [Deleted Scenes]   
..     ...                     ...                                       ...   
992  PG-13 2013-05-26 14:50:58.951             [Trailers, Behind the Scenes]   
993  PG-13 2013-05-26 14:50:58.951                          [Deleted Scenes]   
994      R 2013-05-26 14:50:58.951  [Trailers, Commentaries, Deleted Scenes]   
995      G 2013-05-26 14:50:58.951             [Trailers, Behind the Scenes]   
997  NC-17 2013-05-26 14:50:58.951                          [Deleted Scenes]   

                                              fulltext  
0    'chamber':1 'fate':4 'husband':11 'italian':2 ...  
2    'airport':1 'ancient':18 'confront':14 'epic':...  
3    'boat':20 'bright':1 'conquer':14 'encount':2 ...  
4    'academi':1 'battl':15 'canadian':20 'dinosaur...  
8    'african':1 'chef':11 'dentist':14 'documentar...  
..                                                 ...  
992  'behavior':2 'cow':18 'crocodil':8 'discov':15...  
993  'awe':5 'awe-inspir':4 'boat':13,23 'feminist'...  
994  'amaz':4 'astronaut':11 'berlin':18 'display':...  
995  'administr':12 'boat':8 'boy':17 'databas':11 ...  
997  'boy':16 'canadian':19 'compos':8 'core':2 'fa...  

[463 rows x 13 columns]

## Sorgu 26: 

- select * from film 
where (rental_rate =4.99 and rental_duration=6) or length>50  

- rental_rate i 4.99 olan aynı zamanda rental_duration ı 6 olan veriler ve yanında ek olarak lenght değeri 50 den büyük olan verileri listeler

In [36]:
df_film = pd.read_sql('select * from film', con=engine)

df_film[((df_film["rental_rate"] == 4.99) & (df_film["rental_duration"] == 6)) | (df_film["length"] > 50)]

film_id              title  \
0        133    Chamber Italian   
2          8    Airport Pollock   
3         98  Bright Encounters   
4          1   Academy Dinosaur   
7          4   Affair Prejudice   
..       ...                ...   
994      995        Yentl Idaho   
995      996     Young Language   
996      997         Youth Kick   
997      998       Zhivago Core   
998      999  Zoolander Fiction   

                                           description  release_year  \
0    A Fateful Reflection of a Moose And a Husband ...          2006   
2    A Epic Tale of a Moose And a Girl who must Con...          2006   
3    A Fateful Yarn of a Lumberjack And a Feminist ...          2006   
4    A Epic Drama of a Feminist And a Mad Scientist...          2006   
7    A Fanciful Documentary of a Frisbee And a Lumb...          2006   
..                                                 ...           ...   
994  A Amazing Display of a Robot And a Astronaut w...          2006   
995  A Unbelieveable Yarn of a Boat And a Database ...          2006   
996  A Touching Drama of a Teacher And a Cat who mu...          2006   
997  A Fateful Yarn of a Composer And a Man who mus...          2006   
998  A Fateful Reflection of a Waitress And a Boat ...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
0              1                7         4.99     117             14.99   
2              1                6         4.99      54             15.99   
3              1                4         4.99      73             12.99   
4              1                6         0.99      86             20.99   
7              1                5         2.99     117             26.99   
..           ...              ...          ...     ...               ...   
994            1                5         4.99      86             11.99   
995            1                6         0.99     183              9.99   
996            1                4         0.99     179             14.99   
997            1                6         0.99     105             10.99   
998            1                5         2.99     101             28.99   

    rating             last_update                          special_features  \
0    NC-17 2013-05-26 14:50:58.951                                [Trailers]   
2        R 2013-05-26 14:50:58.951                                [Trailers]   
3    PG-13 2013-05-26 14:50:58.951                                [Trailers]   
4       PG 2013-05-26 14:50:58.951       [Deleted Scenes, Behind the Scenes]   
7        G 2013-05-26 14:50:58.951         [Commentaries, Behind the Scenes]   
..     ...                     ...                                       ...   
994      R 2013-05-26 14:50:58.951  [Trailers, Commentaries, Deleted Scenes]   
995      G 2013-05-26 14:50:58.951             [Trailers, Behind the Scenes]   
996  NC-17 2013-05-26 14:50:58.951             [Trailers, Behind the Scenes]   
997  NC-17 2013-05-26 14:50:58.951                          [Deleted Scenes]   
998      R 2013-05-26 14:50:58.951                [Trailers, Deleted Scenes]   

                                              fulltext  
0    'chamber':1 'fate':4 'husband':11 'italian':2 ...  
2    'airport':1 'ancient':18 'confront':14 'epic':...  
3    'boat':20 'bright':1 'conquer':14 'encount':2 ...  
4    'academi':1 'battl':15 'canadian':20 'dinosaur...  
7    'affair':1 'chase':14 'documentari':5 'fanci':...  
..                                                 ...  
994  'amaz':4 'astronaut':11 'berlin':18 'display':...  
995  'administr':12 'boat':8 'boy':17 'databas':11 ...  
996  'boat':22 'cat':11 'challeng':14 'drama':5 'ki...  
997  'boy':16 'canadian':19 'compos':8 'core':2 'fa...  
998  'ancient':19 'boat':11 'china':20 'discov':14 ...  

[963 rows x 13 columns]

## Sorgu 27:
- select * from film f 
where film_id not in (select film_id from film_actor fa)
- actor bilgisi bulunmayan filmleri listeleme

In [37]:
df_film = pd.read_sql('select * from film', con=engine)
df_film_actor = pd.read_sql('select * from film_actor', con=engine)
df_join = pd.merge(df_film, df_film_actor, on='film_id', how='outer')
df_join.loc[~(df_join['actor_id'].notnull())]


film_id             title  \
1405      257  Drumline Cyclone   
1755      323       Flight Lies   
4390      803  Slacker Liaisons   

                                            description  release_year  \
1405  A Insightful Panorama of a Monkey And a Sumo W...          2006   
1755  A Stunning Character Study of a Crocodile And ...          2006   
4390  A Fast-Paced Tale of a A Shark And a Student w...          2006   

      language_id  rental_duration  rental_rate  length  replacement_cost  \
1405            1                3         0.99     110             14.99   
1755            1                7         4.99     179             22.99   
4390            1                7         4.99     179             29.99   

     rating           last_update_x  \
1405      G 2013-05-26 14:50:58.951   
1755      R 2013-05-26 14:50:58.951   
4390      R 2013-05-26 14:50:58.951   

                                       special_features  \
1405  [Commentaries, Deleted Scenes, Behind the Scenes]   
1755                                         [Trailers]   
4390        [Trailers, Commentaries, Behind the Scenes]   

                                               fulltext  actor_id  \
1405  'canadian':21 'cyclon':2 'drumlin':1 'insight'...       NaN   
1755  'charact':5 'crocodil':9 'flight':1 'lie':2 'm...       NaN   
4390  'ancient':21 'china':22 'crocodil':19 'fast':5...       NaN   

     last_update_y  
1405           NaT  
1755           NaT  
4390           NaT


## Sorgu 28:



- select * from film f 
where film_id  in (select film_id from film_actor fa)
- actor bilgisi bulunan filmleri listeleme

In [38]:
df_film = pd.read_sql('select * from film', con=engine)
df_film_actor = pd.read_sql('select * from film_actor', con=engine)
df_film[df_film["film_id"].isin(df_film_actor["film_id"])]

film_id              title  \
0        133    Chamber Italian   
1        384   Grosse Wonderful   
2          8    Airport Pollock   
3         98  Bright Encounters   
4          1   Academy Dinosaur   
..       ...                ...   
995      996     Young Language   
996      997         Youth Kick   
997      998       Zhivago Core   
998      999  Zoolander Fiction   
999     1000          Zorro Ark   

                                           description  release_year  \
0    A Fateful Reflection of a Moose And a Husband ...          2006   
1    A Epic Drama of a Cat And a Explorer who must ...          2006   
2    A Epic Tale of a Moose And a Girl who must Con...          2006   
3    A Fateful Yarn of a Lumberjack And a Feminist ...          2006   
4    A Epic Drama of a Feminist And a Mad Scientist...          2006   
..                                                 ...           ...   
995  A Unbelieveable Yarn of a Boat And a Database ...          2006   
996  A Touching Drama of a Teacher And a Cat who mu...          2006   
997  A Fateful Yarn of a Composer And a Man who mus...          2006   
998  A Fateful Reflection of a Waitress And a Boat ...          2006   
999  A Intrepid Panorama of a Mad Scientist And a B...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
0              1                7         4.99     117             14.99   
1              1                5         4.99      49             19.99   
2              1                6         4.99      54             15.99   
3              1                4         4.99      73             12.99   
4              1                6         0.99      86             20.99   
..           ...              ...          ...     ...               ...   
995            1                6         0.99     183              9.99   
996            1                4         0.99     179             14.99   
997            1                6         0.99     105             10.99   
998            1                5         2.99     101             28.99   
999            1                3         4.99      50             18.99   

    rating             last_update  \
0    NC-17 2013-05-26 14:50:58.951   
1        R 2013-05-26 14:50:58.951   
2        R 2013-05-26 14:50:58.951   
3    PG-13 2013-05-26 14:50:58.951   
4       PG 2013-05-26 14:50:58.951   
..     ...                     ...   
995      G 2013-05-26 14:50:58.951   
996  NC-17 2013-05-26 14:50:58.951   
997  NC-17 2013-05-26 14:50:58.951   
998      R 2013-05-26 14:50:58.951   
999  NC-17 2013-05-26 14:50:58.951   

                                special_features  \
0                                     [Trailers]   
1                            [Behind the Scenes]   
2                                     [Trailers]   
3                                     [Trailers]   
4            [Deleted Scenes, Behind the Scenes]   
..                                           ...   
995                [Trailers, Behind the Scenes]   
996                [Trailers, Behind the Scenes]   
997                             [Deleted Scenes]   
998                   [Trailers, Deleted Scenes]   
999  [Trailers, Commentaries, Behind the Scenes]   

                                              fulltext  
0    'chamber':1 'fate':4 'husband':11 'italian':2 ...  
1    'australia':18 'cat':8 'drama':5 'epic':4 'exp...  
2    'airport':1 'ancient':18 'confront':14 'epic':...  
3    'boat':20 'bright':1 'conquer':14 'encount':2 ...  
4    'academi':1 'battl':15 'canadian':20 'dinosaur...  
..                                                 ...  
995  'administr':12 'boat':8 'boy':17 'databas':11 ...  
996  'boat':22 'cat':11 'challeng':14 'drama':5 'ki...  
997  'boy':16 'canadian':19 'compos':8 'core':2 'fa...  
998  'ancient':19 'boat':11 'china':20 'discov':14 ...  
999  'ark':2 'boy':12,17 'intrepid':4 'mad':8 'mona...  

[997 rows x 13 columns]

## Sorgu 29:

- select * from film f 
where not exists(select 0 from inventory i where f.film_id=i.film_id)
- herhangi bir inventory listesinde bulunmayan filmleri listele

In [39]:
df_film = pd.read_sql('select * from film', con=engine)
df_inventory = pd.read_sql('select * from inventory', con=engine)
df_join = pd.merge(df_film, df_inventory, on='film_id', how='outer')

df_join.loc[~(df_join['inventory_id'].notnull())]


film_id                   title  \
84         14          Alice Fantasia   
170        33             Apollo Teen   
182        36          Argonauts Town   
190        38           Ark Ridgemont   
202        41    Arsenic Independence   
420        87       Boondock Ballroom   
508       108           Butch Panther   
609       128           Catch Amistad   
691       144     Chinatown Gladiator   
704       148          Chocolate Duck   
808       171    Commandments Express   
894       192        Crossing Divorce   
907       195         Crowds Telemark   
912       198        Crystal Breaking   
994       217              Dazed Punk   
1014      221  Deliverance Mulholland   
1470      318       Firehouse Vietnam   
1504      325           Floats Garden   
1542      332   Frankenstein Stranger   
1668      359      Gladiator Westward   
1797      386               Gump Date   
1881      404           Hate Handicap   
1956      419             Hocus Frida   
2309      495        Kentuckian Giant   
2315      497        Kill Brotherhood   
2797      607             Muppet Mile   
2955      642          Order Betrayed   
3083      669           Pearl Destiny   
3091      671         Perdition Fargo   
3228      701           Psycho Shrunk   
3280      712       Raiders Antitrust   
3281      713           Rainbow Shock   
3421      742           Roof Champion   
3698      801           Sister Freddy   
3699      802             Sky Miracle   
3986      860        Suicides Silence   
4064      874            Tadpole Park   
4215      909        Treasure Command   
4365      943       Villain Desperate   
4397      950            Volume House   
4414      954               Wake Jaws   
4415      955            Walls Artist   

                                            description  release_year  \
84    A Emotional Drama of a A Shark And a Database ...          2006   
170   A Action-Packed Reflection of a Crocodile And ...          2006   
182   A Emotional Epistle of a Forensic Psychologist...          2006   
190   A Beautiful Yarn of a Pioneer And a Monkey who...          2006   
202   A Fanciful Documentary of a Mad Cow And a Woma...          2006   
420   A Fateful Panorama of a Crocodile And a Boy wh...          2006   
508   A Lacklusture Yarn of a Feminist And a Databas...          2006   
609   A Boring Reflection of a Lumberjack And a Femi...          2006   
691   A Brilliant Panorama of a Technical Writer And...          2006   
704   A Unbelieveable Story of a Mad Scientist And a...          2006   
808   A Fanciful Saga of a Student And a Mad Scienti...          2006   
894   A Beautiful Documentary of a Dog And a Robot w...          2006   
907   A Intrepid Documentary of a Astronaut And a Fo...          2006   
912   A Fast-Paced Character Study of a Feminist And...          2006   
994   A Action-Packed Story of a Pioneer And a Techn...          2006   
1014  A Astounding Saga of a Monkey And a Moose who ...          2006   
1470  A Awe-Inspiring Character Study of a Boat And ...          2006   
1504  A Action-Packed Epistle of a Robot And a Car w...          2006   
1542  A Insightful Character Study of a Feminist And...          2006   
1668  A Astounding Reflection of a Squirrel And a Su...          2006   
1797  A Intrepid Yarn of a Explorer And a Student wh...          2006   
1881  A Intrepid Reflection of a Mad Scientist And a...          2006   
1956  A Awe-Inspiring Tale of a Girl And a Madman wh...          2006   
2309  A Stunning Yarn of a Woman And a Frisbee who m...          2006   
2315  A Touching Display of a Hunter And a Secret Ag...          2006   
2797  A Lacklusture Story of a Madman And a Teacher ...          2006   
2955  A Amazing Saga of a Dog And a A Shark who must...          2006   
3083  A Lacklusture Yarn of a Astronaut And a Pastry...          2006   
3091  A Fast-Paced Story of a Car And a Cat who must...          2006   
3228  A Amazing Panorama of a Crocodile And a Explor

## Sorgu 30:
- select * from film f 
where exists(select 0 from inventory i where f.film_id=i.film_id)
- herhangi bir inventory listesine dahil olan filmleri listele

In [40]:
df_film = pd.read_sql('select * from film', con=engine)
df_inventory = pd.read_sql('select * from inventory', con=engine)
df_film[df_film["film_id"].isin(df_inventory["film_id"])]


film_id              title  \
0        133    Chamber Italian   
1        384   Grosse Wonderful   
2          8    Airport Pollock   
3         98  Bright Encounters   
4          1   Academy Dinosaur   
..       ...                ...   
995      996     Young Language   
996      997         Youth Kick   
997      998       Zhivago Core   
998      999  Zoolander Fiction   
999     1000          Zorro Ark   

                                           description  release_year  \
0    A Fateful Reflection of a Moose And a Husband ...          2006   
1    A Epic Drama of a Cat And a Explorer who must ...          2006   
2    A Epic Tale of a Moose And a Girl who must Con...          2006   
3    A Fateful Yarn of a Lumberjack And a Feminist ...          2006   
4    A Epic Drama of a Feminist And a Mad Scientist...          2006   
..                                                 ...           ...   
995  A Unbelieveable Yarn of a Boat And a Database ...          2006   
996  A Touching Drama of a Teacher And a Cat who mu...          2006   
997  A Fateful Yarn of a Composer And a Man who mus...          2006   
998  A Fateful Reflection of a Waitress And a Boat ...          2006   
999  A Intrepid Panorama of a Mad Scientist And a B...          2006   

     language_id  rental_duration  rental_rate  length  replacement_cost  \
0              1                7         4.99     117             14.99   
1              1                5         4.99      49             19.99   
2              1                6         4.99      54             15.99   
3              1                4         4.99      73             12.99   
4              1                6         0.99      86             20.99   
..           ...              ...          ...     ...               ...   
995            1                6         0.99     183              9.99   
996            1                4         0.99     179             14.99   
997            1                6         0.99     105             10.99   
998            1                5         2.99     101             28.99   
999            1                3         4.99      50             18.99   

    rating             last_update  \
0    NC-17 2013-05-26 14:50:58.951   
1        R 2013-05-26 14:50:58.951   
2        R 2013-05-26 14:50:58.951   
3    PG-13 2013-05-26 14:50:58.951   
4       PG 2013-05-26 14:50:58.951   
..     ...                     ...   
995      G 2013-05-26 14:50:58.951   
996  NC-17 2013-05-26 14:50:58.951   
997  NC-17 2013-05-26 14:50:58.951   
998      R 2013-05-26 14:50:58.951   
999  NC-17 2013-05-26 14:50:58.951   

                                special_features  \
0                                     [Trailers]   
1                            [Behind the Scenes]   
2                                     [Trailers]   
3                                     [Trailers]   
4            [Deleted Scenes, Behind the Scenes]   
..                                           ...   
995                [Trailers, Behind the Scenes]   
996                [Trailers, Behind the Scenes]   
997                             [Deleted Scenes]   
998                   [Trailers, Deleted Scenes]   
999  [Trailers, Commentaries, Behind the Scenes]   

                                              fulltext  
0    'chamber':1 'fate':4 'husband':11 'italian':2 ...  
1    'australia':18 'cat':8 'drama':5 'epic':4 'exp...  
2    'airport':1 'ancient':18 'confront':14 'epic':...  
3    'boat':20 'bright':1 'conquer':14 'encount':2 ...  
4    'academi':1 'battl':15 'canadian':20 'dinosaur...  
..                                                 ...  
995  'administr':12 'boat':8 'boy':17 'databas':11 ...  
996  'boat':22 'cat':11 'challeng':14 'drama':5 'ki...  
997  'boy':16 'canadian':19 'compos':8 'core':2 'fa...  
998  'ancient':19 'boat':11 'china':20 'discov':14 ...  
999  'ark':2 'boy':12,17 'intrepid':4 'mad':8 'mona...  

[958 rows x 13 columns]

## Sorgu 31: 

- select count(0) from public.film;
- film tablosundaki toplam kayıt sayısını hesaplar

In [41]:
df_film = pd.read_sql('select * from film', con=engine)

df_film["film_id"].count()

1000

## Sorgu 32: 

- select sum(replacement_cost) from public.film;
- filmlerin toplam replacement_cost değerini hesaplar

In [42]:
df_film = pd.read_sql('select * from film', con=engine)
df_film["replacement_cost"].sum()

19984.0

##  Sorgu 33: 
- select avg(replacement_cost) from public.film;
- filmlerin replacement_cost ortalamasını hesaplar.


In [43]:
df_film = pd.read_sql('select * from film', con=engine)
df_film["replacement_cost"].mean()

19.984000000000144

## Sorgu 34: 

- select min(replacement_cost) from public.film;
- en küçük replacement_cost değerini gösterir. 

In [44]:
df_film = pd.read_sql('select * from film', con=engine)
df_film["replacement_cost"].min()

9.99

## Sorgu 35: 
- select max(replacement_cost) from public.film;
- en büyük replacement_cost değerini gösterir. 

In [45]:
df_film = pd.read_sql('select * from film', con=engine)
df_film["replacement_cost"].max()

29.99

## Sorgu 36:

- select rating, count(0) from public.film group by rating;
- rating e göre film sayılarını hesaplar

In [46]:
df_film = pd.read_sql('select * from film', con=engine)
#df_film["count"]= df_film["rating"].agg("count")

df_film= df_film.groupby("rating").count().reset_index()
df_film

rating  film_id  title  description  release_year  language_id  \
0      G      178    178          178           178          178   
1  NC-17      210    210          210           210          210   
2     PG      194    194          194           194          194   
3  PG-13      223    223          223           223          223   
4      R      195    195          195           195          195   

   rental_duration  rental_rate  length  replacement_cost  last_update  \
0              178          178     178               178          178   
1              210          210     210               210          210   
2              194          194     194               194          194   
3              223          223     223               223          223   
4              195          195     195               195          195   

   special_features  fulltext  
0               178       178  
1               210       210  
2               194       194  
3               223       223  
4               195       195

## Sorgu 37:

- SELECT  EXTRACT (YEAR from p.payment_date) yil,
case EXTRACT (month from p.payment_date) 
when 1 then 'Ocak' 
when 2 then 'Subat'
when 3 then 'Mart'
when 4 then 'Nisan'
when 5 then 'Mayıs'
when 6 then 'Haziran'
when 7 then 'Temmuz'
when 8 then 'Ağustos'
when 9 then 'Eylül'
when 10 then 'Ekim'
when 11 then 'Kasım'
when 12 then 'Aralık' else null end ay,
sum(amount),min(amount),max(amount),avg(amount) ,stddev(amount),variance(amount) FROM payment p 
group by 1,2
order by 1,2
- Aylara göre tutar toplamı, minimum tutar,maximum tutar, tutarın varyansı ve standartsapmasını listele

In [47]:
df_payment = pd.read_sql('select * from payment', con=engine)
df_payment['yil'] = pd.DatetimeIndex(df_payment['payment_date']).year
df_payment['month'] = pd.DatetimeIndex(df_payment['payment_date']).month
df_payment["month_name"]=df_payment.payment_date.dt.month_name()
#df_payment


df_payment.groupby(["yil","month_name"])["amount"].agg(["sum","min","max","mean","std","var"]).reset_index()

yil month_name       sum   min    max      mean       std       var
0  2007      April  28559.46  0.99  11.99  4.228525  2.372554  5.629015
1  2007   February   8351.84  0.99  10.99  4.142778  2.353493  5.538930
2  2007      March  23886.56  0.99  11.99  4.232204  2.362801  5.582830
3  2007        May    514.18  0.00   9.98  2.825165  2.187584  4.785525

## Sorgu 38:

- select c.customer_id,lower(c.first_name),upper(c.last_name),count(p.rental_id)  from public.payment p 
left join rental r ON r.rental_id =p.rental_id 
left join customer c on p.customer_id=c.customer_id   
where r.return_date<=r.rental_date + 5 * INTERVAL '1 day'
group by c.customer_id,c.first_name,c.last_name
having count(p.rental_id)>10
order by c.customer_id 

- Müşteri ad ları küçük harf, soyadları büyük harf olacak şekilde, Kiralam tarihi ile geri dönüş tarihi arası 5 gün olan müşterilerin 10 dan fazla kiralama yaptıkları toplam kiralama sayısını listele

In [48]:
df_customer = pd.read_sql('select customer_id, first_name, last_name from customer', con=engine)
df_payment = pd.read_sql('select rental_id, customer_id from payment', con=engine)
df_rental = pd.read_sql('select rental_id, return_date, rental_date from rental', con=engine)


df_join1 = pd.merge(df_payment, df_rental, on='rental_id', how='left')
df_join2 = pd.merge(df_join1, df_customer, on='customer_id', how='left')

df_join2['last_name'] = df_join2['last_name'].str.upper()
df_join2['first_name'] = df_join2['first_name'].str.lower()

#Kiralama tarihi ile geri dönüş tarihi arası 5 gün 
df_join2['diff_days'] = ((df_join2['return_date'] - df_join2['rental_date']) / np.timedelta64(1, 'D')).round()

df_join2 =df_join2[(df_join2["diff_days"] == 5 ) & (df_join2["rental_id"].count() > 10 )] 
df_join2 = df_join2.groupby(["customer_id", "first_name","last_name"])["rental_id"].agg("count")
df_join2

customer_id  first_name  last_name
1            mary        SMITH        3
2            patricia    JOHNSON      2
4            barbara     JONES        2
5            elizabeth   BROWN        4
6            jennifer    DAVIS        3
                                     ..
595          terrence    GUNDERSON    4
596          enrique     FORSYTHE     3
597          freddie     DUGGAN       5
598          wade        DELVALLE     1
599          austin      CINTRON      2
Name: rental_id, Length: 556, dtype: int64

## Sorgu 39:

- select c.customer_id,c.first_name,c.last_name,sum(p.amount),count(p.payment_id)  from public.payment p 
left join rental r ON r.rental_id =p.rental_id 
left join customer c on p.customer_id=c.customer_id  
where p.amount>=3 and p.amount <=6
group by c.customer_id,c.first_name,c.last_name
order by c.customer_id 
- ödeme tutarı 3 ve 3 den büyük ve 6 ve 6 dan küçük  olan toplam ödeme sayısı ve tutarını müşteri bazında listele

In [49]:
df_customer = pd.read_sql('select customer_id, first_name, last_name from customer', con=engine)
df_payment = pd.read_sql('select rental_id, customer_id, payment_id, amount from payment', con=engine)
df_rental = pd.read_sql('select rental_id, return_date, rental_date from rental', con=engine)


df_join1 = pd.merge(df_payment, df_rental, on='rental_id', how='left')
df_join2 = pd.merge(df_join1, df_customer, on='customer_id', how='left')

df_join2


df_join2[(df_join2["amount"] >= 3 ) & (df_join2["amount"] <= 6 )].groupby(["customer_id", "first_name","last_name"]).agg({"amount" : "sum", "payment_id": "count"})



amount  payment_id
customer_id first_name last_name                    
1           Mary       Smith       71.86          14
2           Patricia   Johnson     60.89          11
3           Linda      Williams    45.91           9
4           Barbara    Jones       36.93           7
5           Elizabeth  Brown       70.85          15
...                                  ...         ...
595         Terrence   Gunderson   38.92           8
596         Enrique    Forsythe    50.89          11
597         Freddie    Duggan      56.89          11
598         Wade       Delvalle    45.91           9
599         Austin     Cintron     13.97           3

[599 rows x 2 columns]

## Sorgu 40: 
- select c.customer_id,c.first_name,c.last_name,sum(p.amount),count(p.payment_id)  from public.payment p 
left join rental r ON r.rental_id =p.rental_id 
left join customer c on p.customer_id=c.customer_id  
where p.amount between 2 and 5
group by c.customer_id,c.first_name,c.last_name
order by c.customer_id 

- ödeme tutarı 2 ile 5 arasında olan toplam ödeme sayısı ve toplam tutara göre müşteri bazında listele

In [50]:
df_customer = pd.read_sql('select customer_id, first_name, last_name from customer', con=engine)
df_payment = pd.read_sql('select rental_id, customer_id, payment_id, amount from payment', con=engine)
df_rental = pd.read_sql('select rental_id, return_date, rental_date from rental', con=engine)


df_join1 = pd.merge(df_payment, df_rental, on='rental_id', how='left')
df_join2 = pd.merge(df_join1, df_customer, on='customer_id', how='left')

df_join2


df_join2[(df_join2["amount"] >= 2 ) & (df_join2["amount"] <= 5 )].groupby(["customer_id", "first_name","last_name"]).agg({"amount" : "sum", "payment_id": "count"})



amount  payment_id
customer_id first_name last_name                    
1           Mary       Smith       62.85          15
2           Patricia   Johnson     45.88          12
3           Linda      Williams    48.88          12
4           Barbara    Jones       39.89          11
5           Elizabeth  Brown       82.80          20
...                                  ...         ...
595         Terrence   Gunderson   65.83          17
596         Enrique    Forsythe    56.87          13
597         Freddie    Duggan      62.85          15
598         Wade       Delvalle    42.90          10
599         Austin     Cintron     31.91           9

[599 rows x 2 columns]

## Sorgu 41: 

- select special_features,special_features[1],special_features[2],special_features[3],special_features[4]  from film f 

- film tablosundaki special_features alanını kolonlara ayırma

In [51]:
df_film = pd.read_sql('select * from film', con=engine)
df_film = pd.DataFrame(df_film['special_features'].tolist()).fillna('').add_prefix('special_features ')
df_film

special_features 0 special_features 1 special_features 2  \
0             Trailers                                         
1    Behind the Scenes                                         
2             Trailers                                         
3             Trailers                                         
4       Deleted Scenes  Behind the Scenes                      
..                 ...                ...                ...   
995           Trailers  Behind the Scenes                      
996           Trailers  Behind the Scenes                      
997     Deleted Scenes                                         
998           Trailers     Deleted Scenes                      
999           Trailers       Commentaries  Behind the Scenes   

    special_features 3  
0                       
1                       
2                       
3                       
4                       
..                 ...  
995                     
996                     
997                     
998                     
999                     

[1000 rows x 4 columns]

## Sorgu 42: 

-  select c2.country,count(p.customer_id),count(p.staff_id),sum(p.amount),count(p.payment_id)  from payment p
    left join staff st on st.staff_id =p.staff_id 
    left join store s on s.store_id =st.staff_id 
    left join address a ON a.address_id =s.address_id 
    left join city c on c.city_id =a.city_id 
    left join country c2 on c2.country_id =c.country_id 
    group by c2.country
- ülke bazında toplam müşteri sayısı,çalışan sayısı,toplam kiralama tutarı, toplam ödeme sayısını listeleyiniz.

In [52]:
df_payment = pd.read_sql('select payment_id, amount, customer_id, staff_id from payment', con=engine)
df_staff = pd.read_sql('select staff_id, store_id from staff', con=engine)
df_store = pd.read_sql('select store_id, address_id from store', con=engine)
df_address = pd.read_sql('select address_id, city_id from address', con=engine)
df_city = pd.read_sql('select city_id, country_id from city', con=engine)
df_country = pd.read_sql('select country_id, country from country', con=engine)
#df_payment
#df_address
df_join1 = pd.merge(df_payment, df_staff, on='staff_id', how='left')
df_join2 = pd.merge(df_join1, df_store, on='store_id', how='left')
df_join3 = pd.merge(df_join2, df_address, on='address_id', how='left')
df_join4 = pd.merge(df_join3, df_city, on='city_id', how='left')
df_join5 = pd.merge(df_join4, df_country, on='country_id', how='left')

df_join5.groupby(["country"]).agg({"amount" : "sum", "payment_id": "count"})
 



amount  payment_id
country                        
Australia  31059.92        7304
Canada     30252.12        7292

## Sorgu 43:

-     select c2.country,extract (year from p.payment_date),extract (month from p.payment_date) ,count(p.customer_id),count(p.staff_id),sum(p.amount),count(p.payment_id)  from payment p
    left join staff st on st.staff_id =p.staff_id 
    left join store s on s.store_id =st.staff_id 
    left join address a ON a.address_id =s.address_id 
    left join city c on c.city_id =a.city_id 
    left join country c2 on c2.country_id =c.country_id 
    group by c2.country,extract (year from p.payment_date),extract (month from p.payment_date)
    order by 6 desc
    
  - ülke bazında toplam müşteri sayısı,çalışan sayısı,toplam kiralama tutarı, toplam ödeme sayısını aylık olarak en çok ödeme tutarından en az ödeme tutarına olacak şekilde listeleyiniz.

In [53]:
df_payment = pd.read_sql('select payment_id, amount, customer_id, staff_id, payment_date from payment', con=engine)
df_staff = pd.read_sql('select staff_id, store_id from staff', con=engine)
df_store = pd.read_sql('select store_id, address_id from store', con=engine)
df_address = pd.read_sql('select address_id, city_id from address', con=engine)
df_city = pd.read_sql('select city_id, country_id from city', con=engine)
df_country = pd.read_sql('select country_id, country from country', con=engine)
#df_payment
#df_address
df_join1 = pd.merge(df_payment, df_staff, on='staff_id', how='left')
df_join2 = pd.merge(df_join1, df_store, on='store_id', how='left')
df_join3 = pd.merge(df_join2, df_address, on='address_id', how='left')
df_join4 = pd.merge(df_join3, df_city, on='city_id', how='left')
df_join5 = pd.merge(df_join4, df_country, on='country_id', how='left')



df_join5['year'] = pd.DatetimeIndex(df_payment['payment_date']).year
df_join5['month'] = pd.DatetimeIndex(df_payment['payment_date']).month

#df_join5

df_join5.groupby(["country","year","month"]).agg({"customer_id" : "count",
                                                  "staff_id": "count",
                                                 "amount" : "sum",
                                                 "payment_id" : "count"}).sort_values("amount").reset_index()

country  year  month  customer_id  staff_id    amount  payment_id
0     Canada  2007      5           95        95    234.09          95
1  Australia  2007      5           87        87    280.09          87
2     Canada  2007      2         1016      1016   4160.84        1016
3  Australia  2007      2         1000      1000   4191.00        1000
4     Canada  2007      3         2817      2817  11776.83        2817
5  Australia  2007      3         2827      2827  12109.73        2827
6     Canada  2007      4         3364      3364  14080.36        3364
7  Australia  2007      4         3390      3390  14479.10        3390

## Sorgu 44: 
-     
   select c."name" as kategori_adi,count(distinct f.film_id),count(distinct a.actor_id) from film f 
    left join film_actor fa ON f.film_id =fa.film_id 
    left join actor a ON a.actor_id =fa.actor_id 
    left join film_category fc on fc.film_id =f.film_id 
    left join category c on c.category_id =fc.category_id 
    group by c."name" 
    
    
 - film kategorileri bazında toplam film sayısı ve toplam aktör sayısını listeler

In [54]:
df_film = pd.read_sql('select film_id from film', con=engine)
df_film_actor = pd.read_sql('select film_id, actor_id from film_actor', con=engine)
df_actor = pd.read_sql('select actor_id from actor', con=engine)
df_film_category = pd.read_sql('select film_id, category_id from film_category', con=engine)
df_category = pd.read_sql('select category_id, name  from category', con=engine)
df_category.rename(columns = {'name':'kategori_adi'}, inplace = True)


df_join1 = pd.merge(df_film, df_film_actor, on='film_id', how='left')
df_join2 = pd.merge(df_join1, df_actor, on='actor_id', how='left')
df_join3 = pd.merge(df_join2, df_film_category, on='film_id', how='left')
df_join4 = pd.merge(df_join3, df_category, on='category_id', how='left')


df_join4.drop_duplicates(subset=['film_id', 'actor_id'], keep='first', inplace = True)




df_join4.groupby(["kategori_adi"]).agg({"film_id" : "count",
                                        "actor_id": "count"})

film_id  actor_id
kategori_adi                   
Action            363       363
Animation         361       361
Children          344       344
Classics          307       307
Comedy            286       286
Documentary       385       385
Drama             351       350
Family            347       347
Foreign           397       397
Games             293       293
Horror            317       317
Music             281       281
New               343       343
Sci-Fi            326       326
Sports            442       441
Travel            322       321

##  Sorgu 45: 

-     
    select c."name" as kategori_adi,l."name" as dil,f.rental_rate ,count(distinct f.film_id),count(distinct a.actor_id) from film f 
    left join film_actor fa ON f.film_id =fa.film_id 
    left join actor a ON a.actor_id =fa.actor_id 
    left join film_category fc on fc.film_id =f.film_id 
    left join category c on c.category_id =fc.category_id 
    left join "language" l on l.language_id =f.language_id 
    where f.rating='PG' 
    group by c."name" ,l."name" ,f.rental_rate
    having count(distinct a.actor_id)>10
    
 - film kategorisi,dil ve rental_rate e göre rating i PG olan ve aktör sayısı toplamı 10 dan fazla olan toplam film sayısı ve toplam aktör sayısını listeler

In [55]:
df_film = pd.read_sql('select film_id, language_id, rental_rate, rating from film', con=engine)
df_film_actor = pd.read_sql('select film_id, actor_id from film_actor', con=engine)
df_actor = pd.read_sql('select actor_id from actor', con=engine)
df_film_category = pd.read_sql('select film_id, category_id from film_category', con=engine)
df_category = pd.read_sql('select category_id, name  from category', con=engine)
df_language = pd.read_sql('select language_id, name  from language', con=engine)

df_category.rename(columns = {'name':'kategori_adi'}, inplace = True)

df_language

df_join1 = pd.merge(df_film, df_film_actor, on='film_id', how='left')
df_join2 = pd.merge(df_join1, df_actor, on='actor_id', how='left')
df_join3 = pd.merge(df_join2, df_film_category, on='film_id', how='left')
df_join4 = pd.merge(df_join3, df_category, on='category_id', how='left')
df_join5 = pd.merge(df_join4, df_language, on='language_id', how='left')

df_join5 = df_join5[(df_join5["rating"] == "PG") & (df_join5["actor_id"].count() > 10)]
df_join5.film_id.unique()
df_join5.actor_id.unique()

df_join5.groupby(["kategori_adi", "name","rental_rate"]).agg({"film_id": "count",
                                                             "actor_id" : "count" })


film_id  actor_id
kategori_adi name                 rental_rate                   
Action       English              0.99              19        19
                                  2.99              32        32
                                  4.99               2         2
Animation    English              0.99               7         7
                                  2.99              42        42
                                  4.99              16        16
Children     English              0.99              25        25
                                  2.99              34        34
                                  4.99              30        30
Classics     English              0.99               9         9
                                  2.99              24        24
                                  4.99              18        18
Comedy       English              0.99              22        22
                                  2.99              33        33
                                  4.99              21        21
Documentary  English              0.99              46        46
                                  2.99              30        30
                                  4.99              21        21
Drama        English              0.99              24        24
                                  2.99               8         8
                                  4.99              11        11
Family       English              0.99              49        49
                                  2.99               9         9
                                  4.99              43        43
Foreign      English              0.99              25        25
                                  2.99              43        43
                                  4.99              16        16
Games        English              0.99               3         3
                                  4.99              18        18
Horror       English              0.99              27        27
                                  2.99              18        18
                                  4.99              29        29
Music        English              0.99              26        26
                                  2.99              18        18
                                  4.99              22        22
New          English              0.99               9         9
                                  2.99              29        29
                                  4.99              20        20
Sci-Fi       English              0.99              22        22
                                  2.99              11        11
                                  4.99              43        43
Sports       English              0.99               9         9
                                  2.99              38        38
                                  4.99              51        51
Travel       English              0.99              29        29
                                  2.99              23        23
                                  4.99              39        39

## Sorgu 46:

-       select     case rating 
    when 'PG' then 1
    when 'R' then 2
    when 'NC-17' then 3
    when 'PG-13' then 4
    when 'G' then 5 else null end Rating_yeni,rating ,count(distinct f.film_id),count(distinct a.actor_id) from film f 
    left join film_actor fa ON f.film_id =fa.film_id 
    left join actor a ON a.actor_id =fa.actor_id 
    left join film_category fc on fc.film_id =f.film_id 
    left join category c on c.category_id =fc.category_id 
    left join "language" l on l.language_id =f.language_id 
    group by     case rating 
    when 'PG' then 1
    when 'R' then 2
    when 'NC-17' then 3
    when 'PG-13' then 4
    when 'G' then 5 else null end,rating 
-  ratinglere id vererek ratinglere göre toplam film sayısı ve toplam aktör sayısını listele

In [56]:
df_film = pd.read_sql('select film_id, language_id, rental_rate, rating from film', con=engine)
df_film_actor = pd.read_sql('select film_id, actor_id from film_actor', con=engine)
df_actor = pd.read_sql('select actor_id from actor', con=engine)
df_film_category = pd.read_sql('select film_id, category_id from film_category', con=engine)
df_category = pd.read_sql('select category_id from category', con=engine)
df_language = pd.read_sql('select language_id from language', con=engine)

df = df_film_actor
df = df.merge(df_film, on='film_id', how='left',suffixes=('', '__2'))
df = df.merge(df_actor, on='actor_id', how='left',suffixes=('', '__2'))
df = df.merge(df_film_category, on='film_id', how='left',suffixes=('', '__2'))
df = df.merge(df_category, on='category_id', how='left',suffixes=('', '__2'))
df = df.merge(df_language, on='language_id', how='left',suffixes=('', '__2'))


df = df.groupby(['rating']).agg({"film_id":"nunique","actor_id":"nunique"}).reset_index()
df['rating_yeni'] = df['rating'].rank(method='dense').astype(int)
df



rating  film_id  actor_id  rating_yeni
0      G      177       199            1
1  NC-17      210       199            2
2     PG      194       199            3
3  PG-13      223       200            4
4      R      193       199            5

## Sorgu 47: 

- select c.first_name,c.last_name,r.rental_date, lead(r.rental_date,1) over (partition by r.customer_id order by r.customer_id,r.rental_date)  from rental r 
left join customer c on c.customer_id =r.customer_id 

- Müşterileri kiralama tarihlerini, bir sonraki kiralama tarihlerini yanlarına getirecek şekilde listeler


In [69]:
df_rental = pd.read_sql('select * from rental', con=engine)
df_customer = pd.read_sql('select * from customer', con=engine)

merged_df = pd.merge(df_rental, df_customer, left_on='customer_id', right_on='customer_id')
merged_df['next_rental_date'] = merged_df.sort_values(by=['customer_id','rental_date']).groupby('customer_id')['rental_date'].shift(-1)
result_df = merged_df[['first_name', 'last_name', 'rental_date', 'next_rental_date']]

result_df

first_name last_name         rental_date    next_rental_date
0          Tommy   Collazo 2005-05-24 22:54:33 2005-06-17 02:50:51
1          Tommy   Collazo 2005-06-17 02:50:51 2005-06-17 09:38:22
2          Tommy   Collazo 2005-06-17 09:38:22 2005-06-17 16:40:33
3          Tommy   Collazo 2005-06-17 16:40:33 2005-06-20 02:39:21
4          Tommy   Collazo 2005-06-20 02:39:21 2005-06-20 12:35:44
...          ...       ...                 ...                 ...
16039    Vanessa      Sims 2005-08-17 22:38:54 2005-08-19 05:39:26
16040    Vanessa      Sims 2005-08-19 05:39:26 2005-08-20 10:48:47
16041    Vanessa      Sims 2005-08-20 10:48:47 2005-08-21 23:11:23
16042    Vanessa      Sims 2005-08-21 23:11:23 2005-08-23 22:19:33
16043    Vanessa      Sims 2005-08-23 22:19:33                 NaT

[16044 rows x 4 columns]

## Sorgu 48: 

- select c.first_name,c.last_name,r.rental_date, lag(r.rental_date,1) over (partition by customer_id order by r.customer_id,r.rental_date)  from rental r 
left join customer c on c.customer_id =r.customer_id 

-  Müşterilerin kiralama tarihlerini bir önceki kiralama tarihlerini yanlarına getirecek şekilde listeler

In [70]:
merged_df = pd.merge(df_rental, df_customer, left_on='customer_id', right_on='customer_id')
merged_df['prev_rental_date'] = merged_df.sort_values(by=['customer_id','rental_date']).groupby('customer_id')['rental_date'].shift(1)
result_df = merged_df[['first_name', 'last_name', 'rental_date', 'prev_rental_date']]
result_df

first_name last_name         rental_date    prev_rental_date
0          Tommy   Collazo 2005-05-24 22:54:33                 NaT
1          Tommy   Collazo 2005-06-17 02:50:51 2005-05-24 22:54:33
2          Tommy   Collazo 2005-06-17 09:38:22 2005-06-17 02:50:51
3          Tommy   Collazo 2005-06-17 16:40:33 2005-06-17 09:38:22
4          Tommy   Collazo 2005-06-20 02:39:21 2005-06-17 16:40:33
...          ...       ...                 ...                 ...
16039    Vanessa      Sims 2005-08-17 22:38:54 2005-08-17 10:59:00
16040    Vanessa      Sims 2005-08-19 05:39:26 2005-08-17 22:38:54
16041    Vanessa      Sims 2005-08-20 10:48:47 2005-08-19 05:39:26
16042    Vanessa      Sims 2005-08-21 23:11:23 2005-08-20 10:48:47
16043    Vanessa      Sims 2005-08-23 22:19:33 2005-08-21 23:11:23

[16044 rows x 4 columns]

## Sorgu 49: 

-  select distinct c.customer_id ,c.first_name,c.last_name,
first_value(r.rental_date) over (partition by r.customer_id order by r.rental_id), 
last_value(r.rental_date) over (partition by r.customer_id order by r.rental_id  rows between unbounded preceding and unbounded following)  
from rental r 
inner join payment p on r.customer_id =p.customer_id and r.rental_id =p.rental_id 
inner join customer c on c.customer_id =p.customer_id 

- Müşterileri,  kiralama id lerine göre ilk ve son  kiralama tarihlerini listeler 

In [71]:
df_rental = pd.read_sql('select * from rental', con=engine)
df_payment = pd.read_sql('select * from payment', con=engine)


result = pd.merge(pd.merge(df_rental, df_payment, on=['customer_id','rental_id']), df_customer, on='customer_id')
result = result.sort_values(by=['customer_id','rental_id'])
result = result.drop_duplicates(subset=['customer_id'])
result['first_rental_date'] = result.groupby(['customer_id'])['rental_date'].transform('first')
result['last_rental_date'] = result.groupby(['customer_id'])['rental_date'].transform('last')
result = result[['customer_id', 'first_name', 'last_name', 'first_rental_date', 'last_rental_date']]
result

customer_id first_name  last_name   first_rental_date  \
501              1       Mary      Smith 2005-06-15 00:54:12   
10649            2   Patricia    Johnson 2005-06-17 20:54:58   
6349             3      Linda   Williams 2005-06-16 01:34:05   
2890             4    Barbara      Jones 2005-06-15 09:31:28   
5858             5  Elizabeth      Brown 2005-06-15 22:03:14   
...            ...        ...        ...                 ...   
244            595   Terrence  Gunderson 2005-06-14 23:47:35   
7331           596    Enrique   Forsythe 2005-06-16 08:58:18   
11469          597    Freddie     Duggan 2005-06-18 14:59:39   
12543          598       Wade   Delvalle 2005-06-20 10:10:29   
11181          599     Austin    Cintron 2005-06-18 06:29:53   

         last_rental_date  
501   2005-06-15 00:54:12  
10649 2005-06-17 20:54:58  
6349  2005-06-16 01:34:05  
2890  2005-06-15 09:31:28  
5858  2005-06-15 22:03:14  
...                   ...  
244   2005-06-14 23:47:35  
7331  2005-06-16 08:58:18  
11469 2005-06-18 14:59:39  
12543 2005-06-20 10:10:29  
11181 2005-06-18 06:29:53  

[599 rows x 5 columns]

## Sorgu 50: 

 
 - select *,ntile(10) over (order by customer_id desc) from customer c
 - Müşteri listesini 10 parçaya böl

In [72]:
df_customer = pd.read_sql('select * from customer', con=engine)

df_customer = df_customer.sort_values(by='customer_id', ascending=False)
df['ntile'] = pd.qcut(range(len(df)), q=10, labels=False) + 1
df_customer

customer_id  store_id first_name  last_name  \
598          599         2     Austin    Cintron   
597          598         1       Wade   Delvalle   
596          597         1    Freddie     Duggan   
595          596         1    Enrique   Forsythe   
594          595         1   Terrence  Gunderson   
..           ...       ...        ...        ...   
5              5         1  Elizabeth      Brown   
4              4         2    Barbara      Jones   
3              3         1      Linda   Williams   
2              2         1   Patricia    Johnson   
1              1         1       Mary      Smith   

                                     email  address_id  activebool  \
598      austin.cintron@sakilacustomer.org         605        True   
597       wade.delvalle@sakilacustomer.org         604        True   
596      freddie.duggan@sakilacustomer.org         603        True   
595    enrique.forsythe@sakilacustomer.org         602        True   
594  terrence.gunderson@sakilacustomer.org         601        True   
..                                     ...         ...         ...   
5       elizabeth.brown@sakilacustomer.org           9        True   
4         barbara.jones@sakilacustomer.org           8        True   
3        linda.williams@sakilacustomer.org           7        True   
2      patricia.johnson@sakilacustomer.org           6        True   
1            mary.smith@sakilacustomer.org           5        True   

    create_date             last_update  active  
598  2006-02-14 2013-05-26 14:49:45.738       1  
597  2006-02-14 2013-05-26 14:49:45.738       1  
596  2006-02-14 2013-05-26 14:49:45.738       1  
595  2006-02-14 2013-05-26 14:49:45.738       1  
594  2006-02-14 2013-05-26 14:49:45.738       1  
..          ...                     ...     ...  
5    2006-02-14 2013-05-26 14:49:45.738       1  
4    2006-02-14 2013-05-26 14:49:45.738       1  
3    2006-02-14 2013-05-26 14:49:45.738       1  
2    2006-02-14 2013-05-26 14:49:45.738       1  
1    2006-02-14 2013-05-26 14:49:45.738       1  

[599 rows x 10 columns]

## Sorgu 51: 

- select count(0),c."name"  from film f
left join film_category fc on f.film_id =fc.film_id 
left join category c on c.category_id=fc.category_id 
where f.title  like 'Ca%'
group by c.name 
- film ismi başı 'Ca' ile başlayan filmlerin categori bazında sayıları

In [73]:
df_film_category = pd.read_sql('select * from film_category', con=engine)
df_film = pd.read_sql('select * from film', con=engine)
df_category = pd.read_sql('select * from category', con=engine)

df = df_film_category

df = df.merge(df_film, on='film_id', how='left',suffixes=('', '__2'))
df = df.merge(df_category, on='category_id', how='left',suffixes=('', '__2'))

df = df[df['title'].str.startswith('Ca')]
df = df.groupby(['name']).agg({"film_id":"count"})

df

film_id
name                
Action             3
Animation          2
Children           2
Classics           1
Comedy             2
Documentary        1
Foreign            2
Games              1
Horror             1
Sci-Fi             1
Sports             2
Travel             2

## Sorgu 52: 

- select count(0),c."name"  from film f
left join film_category fc on f.film_id =fc.film_id 
left join category c on c.category_id=fc.category_id 
where f.title  like '%n'
group by c.name

- film ismi sonu 'n' ile biten filmlerin categori bazında sayıları

In [74]:
df = df_film_category
df = df.merge(df_film, on='film_id', how='left',suffixes=('', '__2'))
df = df.merge(df_category, on='category_id', how='left',suffixes=('', '__2'))

df = df[df['title'].str.endswith('n')]
df = df.groupby(['name']).agg({"film_id":"count"})

df

film_id
name                
Action            10
Animation          8
Children           7
Classics           8
Comedy             5
Documentary        5
Drama              7
Family             4
Foreign            7
Games              6
Horror             6
Music              6
New                8
Sci-Fi             9
Sports            10
Travel             6

## Sorgu 53: 


- select count(0),c."name"  from film f
left join film_category fc on f.film_id =fc.film_id 
left join category c on c.category_id=fc.category_id 
where f.title  like '%a%'
group by c.name
- film ismi içinde 'a' geçen filmlerin categori bazında sayıları


In [75]:
df = df_film_category
df = df.merge(df_film, on='film_id', how='left',suffixes=('', '__2'))
df = df.merge(df_category, on='category_id', how='left',suffixes=('', '__2'))

df = df[df['title'].str.contains('a')]
df = df.groupby(['name']).agg({"film_id":"count"})

df

film_id
name                
Action            43
Animation         49
Children          45
Classics          40
Comedy            39
Documentary       46
Drama             37
Family            55
Foreign           46
Games             49
Horror            43
Music             31
New               52
Sci-Fi            42
Sports            51
Travel            38

## Sorgu 54: 

- select c."name" kategori_adi,count(f.film_id) as film_sayisias  from public.film f 
left join film_category fc on fc.film_id=f.film_id  
left join public.category c on c.category_id=fc.category_id  
group by c."name"
order by c."name" 

- Kategori bazında film sayıları 

In [76]:
df = df_film_category
df = df.merge(df_film, on='film_id', how='left',suffixes=('', '__2'))
df = df.merge(df_category, on='category_id', how='left',suffixes=('', '__2'))

df = df.groupby(['name']).agg({"film_id":"count"})
df = df.sort_values(by='name')

df

film_id
name                
Action            64
Animation         66
Children          60
Classics          57
Comedy            58
Documentary       68
Drama             62
Family            69
Foreign           73
Games             61
Horror            56
Music             51
New               63
Sci-Fi            61
Sports            74
Travel            57

## Sorgu 55: 

- select f.title,string_agg((a.first_name||' '||a.last_name),';'),array_agg(a.first_name||' '||a.last_name)  from public.film f 
left join public.film_actor fa on fa.film_id = f.film_id 
left join public.actor a on a.actor_id =fa.actor_id 
group by f.title 

- Tek satır halinde Film listesi yanında liste olarak bilreştirilmiş aktör kolonu


In [89]:
df_film = pd.read_sql('select title, film_id from film', con=engine)
df_actor = pd.read_sql('select first_name, last_name, actor_id from actor', con=engine)
df_film_actor = pd.read_sql('select * from film_actor', con=engine)


df = df_film.merge(df_film_actor, on='film_id', how='left')\
           .merge(df_actor, on='actor_id', how='left')

df['full_name'] = df['first_name'].astype(str) + " " + df['last_name'].astype(str)

df = df.groupby('title')\
           .agg(actors=('full_name', lambda x: ';'.join(x)),
                actor_list=('full_name', lambda x: x.tolist()))\
           .reset_index()

df


title                                             actors  \
0     Academy Dinosaur  Penelope Guiness;Christian Gable;Lucille Tracy...   
1       Ace Goldfinger  Bob Fawcett;Minnie Zellweger;Sean Guiness;Chri...   
2     Adaptation Holes  Nick Wahlberg;Bob Fawcett;Cameron Streep;Ray J...   
3     Affair Prejudice  Jodie Degeneres;Scarlett Damon;Kenneth Pesci;F...   
4          African Egg  Gary Phoenix;Dustin Tautou;Matthew Leigh;Matth...   
..                 ...                                                ...   
995     Young Language  Ed Chase;Julia Mcqueen;James Pitt;Christopher ...   
996         Youth Kick  Sandra Kilmer;Val Bolger;Scarlett Bening;Ian T...   
997       Zhivago Core  Uma Wood;Nick Stallone;Gary Penn;Salma Nolte;K...   
998  Zoolander Fiction  Carmen Hunt;Mary Tandy;Penelope Cronyn;Whoopi ...   
999          Zorro Ark               Ian Tandy;Nick Degeneres;Lisa Monroe   

                                            actor_list  
0    [Penelope Guiness, Christian Gable, Lucille Tr...  
1    [Bob Fawcett, Minnie Zellweger, Sean Guiness, ...  
2    [Nick Wahlberg, Bob Fawcett, Cameron Streep, R...  
3    [Jodie Degeneres, Scarlett Damon, Kenneth Pesc...  
4    [Gary Phoenix, Dustin Tautou, Matthew Leigh, M...  
..                                                 ...  
995  [Ed Chase, Julia Mcqueen, James Pitt, Christop...  
996  [Sandra Kilmer, Val Bolger, Scarlett Bening, I...  
997  [Uma Wood, Nick Stallone, Gary Penn, Salma Nol...  
998  [Carmen Hunt, Mary Tandy, Penelope Cronyn, Who...  
999           [Ian Tandy, Nick Degeneres, Lisa Monroe]  

[1000 rows x 3 columns]

##  Sorgu 56:

- select 'müsteri_id:'||c.customer_id||' / '||c.first_name||' '||c.last_name as customer_name,count(r.rental_id) as kiralanma_sayisi from public.rental r 
left join public.customer c on r.customer_id=c.customer_id
group by 1
- Müşteri bazında hangi filmden kaç kere kiraladığı

In [79]:
df_customer = pd.read_sql('select customer_id, first_name, last_name from customer', con=engine)
df_rental = pd.read_sql('select rental_id, customer_id  from rental', con=engine)


df_join1 = pd.merge(df_customer, df_rental, on='customer_id', how='left')
df_join1.rental_id.unique()

df_join1['ad_soyad'] = df_join1['first_name'].astype(str) + ' ' + df_join1['last_name']
df_join1["customer_name"]= "musteri_id:" +  df_join1.customer_id.astype(str) + ' / ' + df_join1.ad_soyad

df = pd.DataFrame(df_join1.groupby("customer_name")["rental_id"].agg("count")).reset_index()
df.rename(columns={"rental_id" : "kiralanma_sayisi"})


customer_name  kiralanma_sayisi
0          musteri_id:1 / Mary Smith                32
1     musteri_id:10 / Dorothy Taylor                25
2       musteri_id:100 / Robin Hayes                24
3       musteri_id:101 / Peggy Myers                24
4      musteri_id:102 / Crystal Ford                33
..                               ...               ...
594     musteri_id:95 / Paula Bryant                18
595  musteri_id:96 / Diana Alexander                27
596    musteri_id:97 / Annie Russell                18
597  musteri_id:98 / Lillian Griffin                25
598       musteri_id:99 / Emily Diaz                24

[599 rows x 2 columns]

## Sorgu 57: 

- select 'müsteri_id:'||c.customer_id||' / '||c.first_name||' '||c.last_name as customer_name,to_char(rental_date,'YYYY-MM') ay,count(r.rental_id) as kiralanma_sayisi from public.rental r 
left join public.customer c on r.customer_id=c.customer_id
group by 1,2
order by 1,2

- Müşteri bazında aylık periyotlarda kaç film kiraladığı 


In [80]:
df_customer = pd.read_sql('select customer_id, first_name, last_name from customer', con=engine)
df_rental = pd.read_sql('select rental_id, customer_id, rental_date  from rental', con=engine)


df_join1 = pd.merge(df_customer, df_rental, on='customer_id', how='left')
df_join1.rental_id.unique()

df_join1['ad_soyad'] = df_join1['first_name'].astype(str) + ' ' + df_join1['last_name']
df_join1["customer_name"]= "musteri_id:" +  df_join1.customer_id.astype(str) + ' / ' + df_join1.ad_soyad

df_join1["ay"]=df_join1.rental_date.dt.year.astype(str) + "-" + df_join1.rental_date.dt.month.astype(str)

df = pd.DataFrame(df_join1.groupby(["customer_name", "ay"])["rental_id"].agg("count")).reset_index()

df.sort_values("ay")
df.rename(columns={"rental_id" : "kiralanma_sayisi"})


customer_name      ay  kiralanma_sayisi
0          musteri_id:1 / Mary Smith  2005-5                 2
1          musteri_id:1 / Mary Smith  2005-6                 7
2          musteri_id:1 / Mary Smith  2005-7                12
3          musteri_id:1 / Mary Smith  2005-8                11
4     musteri_id:10 / Dorothy Taylor  2005-5                 1
...                              ...     ...               ...
2461      musteri_id:99 / Emily Diaz  2005-5                 1
2462      musteri_id:99 / Emily Diaz  2005-6                 2
2463      musteri_id:99 / Emily Diaz  2005-7                15
2464      musteri_id:99 / Emily Diaz  2005-8                 5
2465      musteri_id:99 / Emily Diaz  2006-2                 1

[2466 rows x 3 columns]

## Sorgu 58: 

- select 'müsteri_id:'||c.customer_id||' / '||c.first_name||' '||c.last_name as customer_name,to_char(rental_date,'YYYY-MM') ay,count(r.rental_id) as kiralanma_sayisi from public.rental r 
left join public.customer c on r.customer_id=c.customer_id
group by 1,2
order by 3 desc 

- Aylık periyotlar bazında en çok film kiralayan müşterilerin listesi 



In [81]:
df_customer = pd.read_sql('select customer_id, first_name, last_name from customer', con=engine)
df_rental = pd.read_sql('select rental_id, customer_id, rental_date  from rental', con=engine)


df_join1 = pd.merge(df_customer, df_rental, on='customer_id', how='left')
df_join1.rental_id.unique()

df_join1['ad_soyad'] = df_join1['first_name'].astype(str) + ' ' + df_join1['last_name']
df_join1["customer_name"]= "musteri_id:" +  df_join1.customer_id.astype(str) + ' / ' + df_join1.ad_soyad

df_join1["ay"]=df_join1.rental_date.dt.year.astype(str) + "-" + df_join1.rental_date.dt.month.astype(str)

df = pd.DataFrame(df_join1.groupby(["customer_name", "ay"])["rental_id"].agg("count")).reset_index()

df.sort_values("rental_id", ascending=False,inplace=True)
df.rename(columns={"rental_id" : "kiralanma_sayisi"})

customer_name      ay  kiralanma_sayisi
224       musteri_id:148 / Eleanor Hunt  2005-7                22
19        musteri_id:102 / Crystal Ford  2005-7                21
629        musteri_id:236 / Marcia Dean  2005-7                20
2357      musteri_id:75 / Tammy Sanders  2005-7                20
1221      musteri_id:366 / Brandon Huey  2005-7                19
...                                 ...     ...               ...
1473         musteri_id:421 / Lee Hawks  2006-2                 1
1474  musteri_id:422 / Melvin Ellington  2005-5                 1
1478  musteri_id:422 / Melvin Ellington  2006-2                 1
1482     musteri_id:424 / Kyle Spurlock  2005-5                 1
2465         musteri_id:99 / Emily Diaz  2006-2                 1

[2466 rows x 3 columns]

## Sorgu 59: 

- select * from (select row_number() over (partition by b.yil,b.quarter order by quarter,b.total_amount desc) as sira,b.yil,b.quarter,b.film_name,b.total_amount from( 
select EXTRACT (YEAR from p.payment_date) yil,EXTRACT (QUARTER from p.payment_date)  quarter,f.title  film_name, sum(p.amount)  total_amount
from public.payment p 
left join rental r on r.rental_id =p.rental_id 
left join inventory i on i.inventory_id  =r.inventory_id
left join public.film f  on f.film_id =i.film_id  
group by 1,2,3) b) t
where t.sira<=5

- Quarter bazında en çok gelir getiren ilk 5 film gelirleri ile birlikte


In [82]:
# Gerekli tablolar: 
df_payment = pd.read_sql('select payment_date, payment, amount, rental_id  from payment', con=engine)
df_rental = pd.read_sql('select rental_id, inventory_id from rental', con=engine)
df_inventory = pd.read_sql('select inventory_id, film_id from inventory', con=engine)
df_film = pd.read_sql('select title, film_id  from film', con=engine)

df_join1 = pd.merge(df_payment, df_rental, on='rental_id', how='left')
df_join2 = pd.merge(df_join1, df_inventory, on='inventory_id', how='left')
df_join3 = pd.merge(df_join2, df_film, on='film_id', how='left')
df_join3["quarter"] = df_join3['payment_date'].dt.quarter

df_join3["yil"]=df_join1.payment_date.dt.year.astype(str)
df_join3.rename(columns= {"title" : "film_name"}, inplace = True)
df_join3["sira"] =  df_join3.sort_values(["yil",'quarter'], ascending=[True,False]).groupby(['yil']).cumcount() + 1



df_join3.groupby(["yil", "quarter", "film_name", ]).agg({"amount" :"sum"}).reset_index()
df = df_join3.groupby(["yil", "quarter", "film_name"]).agg({"amount" :"sum"}).reset_index()
#df
df.sort_values("amount", ascending= False).head(10)



yil  quarter         film_name  amount
841   2007        1  Telegraph Voyage  129.86
930   2007        1         Wife Turn  120.85
957   2007        1         Zorro Ark  107.84
1688  2007        2    Saturday Lambs  103.87
1813  2007        2       Titans Jerk  102.85
1394  2007        2    Innocent Usual   98.87
807   2007        1       Steel Santa   97.85
641   2007        1  Pelican Comforts   96.87
1378  2007        2     Hustler Party   95.90
420   2007        1     Hustler Party   94.88

## Sorgu 60: 
- select * from (select row_number() over (partition by b.quarter order by quarter,b.total_amount desc) as sira,b.yil,b.quarter,b.city,b.total_amount from( 
select EXTRACT (YEAR from p.payment_date) yil,EXTRACT (QUARTER from p.payment_date)  quarter,c2.city , sum(p.amount)  total_amount
from public.payment p 
left join customer c on c.customer_id=p.customer_id 
left join address a on a.address_id =c.address_id 
left join city c2 on c2.city_id =a.city_id 
group by 1,2,3) b) t
where t.sira<=5

- Quarter bazında en çok gelir getiren ilk 5 film gelirleri ile birlikte şehirlere göre dağılımı


In [88]:
df_payment = pd.read_sql('select *  from payment', con=engine)
df_customer = pd.read_sql('select  * from customer', con=engine)
df_address = pd.read_sql('select  * from address', con=engine)
df_city = pd.read_sql('select  * from city', con=engine)


df = df_payment
df["yil"] = df["payment_date"].dt.year
df["quarter"] = df["payment_date"].dt.quarter
df = df.merge(df_customer, on="customer_id")
df = df.merge(df_address, on="address_id")
df = df.merge(df_city, on="city_id")

df = df.groupby(["yil", "quarter", "city"]).agg({"amount": "sum"}).reset_index()
df["sira"] = df.groupby("quarter")["amount"].rank(ascending=False)
df = df.loc[df["sira"] <= 5]
df = df[["yil", "quarter", "city", "amount", "sira"]]
df



yil  quarter           city  amount  sira
95    2007        1     Cape Coral  118.78   1.0
304   2007        1         London  110.75   4.0
420   2007        1  Richmond Hill  109.77   5.0
431   2007        1    Saint-Denis  110.77   3.0
514   2007        1        Tangail  111.78   2.0
620   2007        2      Apeldoorn   96.81   4.0
796   2007        2        Hodeida   96.83   3.0
928   2007        2      Molodetno   93.82   5.0
1028  2007        2    Saint-Denis  100.78   1.0
1044  2007        2     Santa Rosa   97.81   2.0

## Sorgu 61: 

-  select * from (select row_number() over (partition by b.yil,b.ay order by b.total_payment desc) as sira,b.yil,b.ay,b.staff_id,b.total_payment  

    from( 
    select EXTRACT (YEAR from p.payment_date) yil,EXTRACT (month from p.payment_date)  ay,s.staff_id , count(p.payment_id)  total_payment
    from public.payment p 
    left join staff s  on s.staff_id=p.staff_id  
    group by 1,2,3) b) t
    where t.sira=1

-  Aylık periyotlara göre en çok satış yapan personel


In [84]:
df_payment = pd.read_sql('select *from payment', con=engine)
df_staff = pd.read_sql('select * from staff', con=engine)
df_join1 = pd.merge(df_payment, df_staff, on='staff_id', how='left')

df_join1["yil"]=df_join1.payment_date.dt.year.astype(int)
df_join1["ay"]=df_join1.payment_date.dt.month.astype(int)
df_join1["sira"] =df_join1.index


#df_join1

df = df_join1[(df_join1["staff_id"] == 1)].groupby(["yil","ay","staff_id"])["amount"].agg("sum")
df =  pd.DataFrame(df)
df



amount
yil  ay staff_id          
2007 2  1          4160.84
     3  1         11776.83
     4  1         14080.36
     5  1           234.09

## Sorgu 62: 

- SELECT rental_rate,
       json_object_agg(rental_duration,total  ORDER BY rental_duration)
   FROM (
     SELECT rental_rate, rental_duration, count(film_id) AS total
        FROM film
        GROUP BY rental_rate,rental_duration
   ) s
  GROUP BY rental_rate
  ORDER BY rental_rate;

- rental ratelere göre json objesi şeklinde rental_duration'a ait toplam film sayıları


In [85]:
df_film = pd.read_sql('select * from film', con=engine)



df = df_film.groupby(["rental_rate", "rental_duration"])["film_id"].agg("count").reset_index()
df =  pd.DataFrame(df)





df['result'] = df.apply(lambda x: {x.rental_duration: x.film_id}, axis=1)

columns = ["rental_rate", "result"]

df[columns]

## soruda eksik var 0.99 değerinin hepsi yanyana olmalıydı !!! 

rental_rate       result
0          0.99  {3.0: 78.0}
1          0.99  {4.0: 72.0}
2          0.99  {5.0: 56.0}
3          0.99  {6.0: 76.0}
4          0.99  {7.0: 59.0}
5          2.99  {3.0: 63.0}
6          2.99  {4.0: 61.0}
7          2.99  {5.0: 59.0}
8          2.99  {6.0: 70.0}
9          2.99  {7.0: 70.0}
10         4.99  {3.0: 62.0}
11         4.99  {4.0: 70.0}
12         4.99  {5.0: 76.0}
13         4.99  {6.0: 66.0}
14         4.99  {7.0: 62.0}

## Sorgu 63: 

- select * from (select dense_rank() over (partition by tt.first_name,tt.last_name,store_id order by sure desc ) as sira,tt.*
from (select c.first_name,c.last_name , f.title ,s2.store_id ,age(return_date,rental_date) sure  from public.rental r 
inner join payment p on p.rental_id=r.rental_id and r.customer_id =p.customer_id and r.staff_id=p.staff_id  
 inner join staff s on s.staff_id =p.staff_id 
 inner join store s2 on s2.store_id =s.store_id  
 inner join inventory i on i.inventory_id=r.inventory_id  and i.store_id =s.store_id 
 inner join film f on f.film_id =i.film_id 
 inner join customer c on r.customer_id =c.customer_id 
 order by 1,2,4,3) tt where  sure is not null ) sonuc
 where sonuc.sira=1

- Bir müşterinin bir storede en uzun süre kiraladığı film ve süresi 


## Sorgu 64: 

- select b.customer_id,b.first_name,b.last_name,max(sure),min(sure)
from (select c.customer_id,c.first_name,c.last_name,age(r.rental_date, lag(r.rental_date,1) over (partition by r.customer_id order by r.customer_id,r.rental_date)) sure  from rental r 
left join customer c on c.customer_id =r.customer_id) b
where b.sure is not null and b.customer_id=101
group by b.customer_id,b.first_name,b.last_name

- Müşterilerin iki kiralama tarihi arasındaki minimum ve maksimum süreleri

In [65]:
df_customer = pd.read_sql('select customer_id, first_name, last_name  from customer', con=engine)
df_rental = pd.read_sql('select rental_date, customer_id  from rental', con=engine)


df_join1 = pd.merge(df_customer, df_rental, on='customer_id', how='left')
df_join1["sure"] = df_join1.groupby("customer_id")['rental_date'].shift(1).diff()
df_join1["max"] =df_join1.groupby(["customer_id"]).agg({"sure" : "max"})
df_join1["min"] =df_join1.groupby(["customer_id"]).agg({"sure" : "min"})
df_join1 = df_join1[(df_join1.customer_id == 101)]
df_join1 = df_join1.groupby(["customer_id", "first_name", "last_name"]).agg({"sure" : "max", "sure" : "min" })


df_join1



sure
customer_id first_name last_name                    
101         Peggy      Myers     -181 days +09:52:50